// GENERATED by scripts/bake-gear.mjs. Do not edit; edit GEAR there and re-run.
import type { Slot } from './loot'

/** Sheet cell [col, row] for each slot's base types, in base-index order. */
export const GEAR_TILES: Record<Slot, ReadonlyArray<readonly [number, number]>> = {
  helm: [[39, 12] /* Dome Helm */, [38, 12] /* Horned Helm */, [40, 12] /* Bucket Helm */, [41, 12] /* Great Helm */, [8, 30] /* Feathered Hat */, [26, 23] /* Crown */],
  weapon: [[36, 6] /* Short Sword */, [26, 6] /* Broadsword */, [34, 6] /* Katana */, [44, 6] /* Dagger */, [26, 9] /* Battle Axe */, [26, 7] /* Mace */, [42, 13] /* Staff */, [28, 8] /* Spear */, [26, 10] /* Bow */],
  armor: [[0, 26] /* Tunic */, [4, 26] /* Scale Mail */, [15, 26] /* Chainmail */, [16, 26] /* Plate */, [13, 28] /* Robe */, [20, 28] /* Mantle */],
  shield: [[26, 12] /* Heater Shield */, [28, 12] /* Round Shield */, [27, 12] /* Tower Shield */],
  ring: [[11, 43] /* Band */, [12, 43] /* Signet */, [13, 43] /* Seal Ring */, [11, 44] /* Gemmed Ring */, [13, 44] /* Loop */],
  boots: [[5, 29] /* Boots */, [6, 29] /* Sturdy Boots */, [12, 29] /* Tall Boots */, [13, 29] /* Greaves */],
  amulet: [[0, 43] /* Amulet */, [2, 43] /* Talisman */, [0, 44] /* Pendant */, [2, 44] /* Charm */, [6, 44] /* Medallion */, [37, 23] /* Necklace */],
}

/** The loot chest icon. */
export const CHEST_TILE: readonly [number, number] = [26, 19]
