// AUTO-GENERATED by scripts/extract-village-catalog.mjs — do not edit by hand.
// Source of truth: the CATALOG literal inside public/village/index.html
// (the onebit-kit Village Kit Builder). Re-extract after updating the tool.
//
// Each part is ASCII-authored pixel art: rows of characters, one per art
// pixel. '.' empty, 'X' ink, 'S' shade (dither), 'H' highlight (paper).

export interface VillagePart {
  name: string
  w: number
  h: number
  cat: string
  kind: string
  rows: string[]
  /** anchor: canopy attach px; top/stretch: trunk grow rules; drop: roof sink */
  meta?: { anchor?: [number, number]; top?: number; stretch?: number; drop?: number }
}

export const CATALOG: VillagePart[] = [
 {
  "name": "anvil",
  "w": 15,
  "h": 14,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "....XXX........",
   "....XXX........",
   ".....X.........",
   "...............",
   "...............",
   "XXXXXXXXXXXXXX.",
   ".XXHXXX..XXXXXX",
   "..XXXXXXXXHXXX.",
   "....XXXXXXX....",
   ".....XXXXX.....",
   ".....XXHXX.....",
   "....XXXXXXX....",
   "...XXHXXXXXX...",
   "..XXXXXXXXXXX.."
  ]
 },
 {
  "name": "awning",
  "w": 12,
  "h": 10,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "XX..........",
   "..XX........",
   "XX..XX......",
   "XXXX..XX....",
   "..X.XX..XX..",
   "XXXX..XX..XX",
   "X.XX..XXXX..",
   "XX.XXXXX.X..",
   "XXX.XXX.XX..",
   "XXXXXXXXXX.."
  ]
 },
 {
  "name": "barrel",
  "w": 7,
  "h": 7,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   ".XXXXX.",
   "XXXXXXX",
   "X.X.X.X",
   "XXXXXXX",
   "X.X.X.X",
   "XXXXXXX",
   ".XXXXX."
  ]
 },
 {
  "name": "battlement",
  "w": 11,
  "h": 5,
  "cat": "roof",
  "kind": "sprite",
  "rows": [
   "S.S.S.S.S.S",
   "SSSSSSSSSSS",
   "SSSSS.SSSSS",
   "SSSSS.SSSSS",
   "SSSSSSSSSSS"
  ]
 },
 {
  "name": "book",
  "w": 19,
  "h": 10,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   ".XXXXXXXX.XXXXXXXX.",
   "X........X........X",
   "X..XXXX..X..XXXX..X",
   "X........X........X",
   "X..XXX...X..XXXXX.X",
   "X........X........X",
   "X..XXXXX.X..XXX...X",
   "X........X........X",
   "XXXXXXXXXXXXXXXXXXX",
   ".XXXXXXXXXXXXXXXXX."
  ]
 },
 {
  "name": "bookstack",
  "w": 17,
  "h": 12,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "...XXXXXXXXXXX...",
   "...X.........X...",
   "...X.XXXXXXX.X...",
   "...XXXXXXXXXXX...",
   ".XXXXXXXXXXXXXXX.",
   ".X.............X.",
   ".X.XXX...XXXXX.X.",
   ".XXXXXXXXXXXXXXX.",
   "XXXXXXXXXXXXXXXXX",
   "X...............X",
   "X.XXXXXX..XXXXX.X",
   "XXXXXXXXXXXXXXXXX"
  ]
 },
 {
  "name": "bucket",
  "w": 5,
  "h": 4,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "XXXXX",
   "X...X",
   "X.X.X",
   ".XXX."
  ]
 },
 {
  "name": "bush",
  "w": 10,
  "h": 6,
  "cat": "tree",
  "kind": "sprite",
  "rows": [
   "....G.G...",
   "..G.GGG.G.",
   ".GGGGGGGG.",
   "G.GGG.GGGG",
   ".GGGGGGGG.",
   "..GG.GGG.."
  ]
 },
 {
  "name": "campfire",
  "w": 11,
  "h": 11,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "......X....",
   ".....X.....",
   "....X.X....",
   ".....X.....",
   "....X.X....",
   ".....X.....",
   "....X.X....",
   "..XX.X.XX..",
   ".X..X.X..X.",
   "X..XX.XX..X",
   "...XXXXX..."
  ]
 },
 {
  "name": "canopy_gnarled",
  "w": 13,
  "h": 8,
  "cat": "tree",
  "kind": "canopy",
  "rows": [
   "...G.......G.",
   "....G.G.....G",
   "...G.G.G.G.G.",
   ".G....G...G..",
   "G............",
   ".............",
   "..........G..",
   ".G.........G."
  ],
  "meta": {
   "anchor": [
    4,
    3
   ]
  }
 },
 {
  "name": "canopy_oak",
  "w": 32,
  "h": 22,
  "cat": "tree",
  "kind": "canopy",
  "rows": [
   "................G...............",
   ".................GG.G...........",
   "...............GG.GGGG..........",
   ".............GG.GGGGG...........",
   "............G.GGGGGG.G.G........",
   ".........G.G.GGGGGGGG.G.........",
   "..........G.GGGGGGGGGG.G........",
   ".......G..GGGG.GGGGGGGG.G...G...",
   "........G.GGG.GGGGGGGG.G.GGG....",
   ".........G.GGGGGGGGGG.GGGGG.G...",
   "...G...GG.GGGGG.GGGGGGGGGGGGGG.G",
   "....GGG.GGGGGGGG.GGGGGGGGGGGGGG.",
   "...GGGGGGGGGG.GGG.GGGGGGGGGGGGG.",
   "...GGGGGGGGGGG.G.GGGGGGGGGGGG.G.",
   "...GGGGGGGGGGGGGG.G.GGGGGGGGGG..",
   "G.G.GGGG.GGGGGGGGG.G.G.G.GGGG..G",
   ".G.GGGGGGGGG.GGGGGGGGGG.GG.G.GG.",
   ".GGGGGGG.GGGG....GGGGGGGGGG.G...",
   ".GGGGGG.GGG.......GG.GGG.G...G..",
   "..GGG.GG..................G.....",
   "...GGG..G.......................",
   "..G............................."
  ],
  "meta": {
   "anchor": [
    15,
    18
   ]
  }
 },
 {
  "name": "canopy_pine",
  "w": 11,
  "h": 16,
  "cat": "tree",
  "kind": "canopy",
  "rows": [
   ".....G.....",
   "....GG.G...",
   ".....GG....",
   "...G.GG....",
   "....GG.G...",
   ".....GG....",
   "..G.GGG.G..",
   "...GGGGG...",
   "....GGGG.G.",
   "..G.GGG....",
   "...G.GGG...",
   ".GG.GGG.G..",
   "...GGGGG...",
   "....GGGG.GG",
   "..GGGGGGG..",
   "GG..G.GG.G."
  ],
  "meta": {
   "anchor": [
    5,
    15
   ]
  }
 },
 {
  "name": "canopy_round",
  "w": 12,
  "h": 8,
  "cat": "tree",
  "kind": "canopy",
  "rows": [
   ".....G.G....",
   "....G.GGG...",
   ".G.G.GGG.GG.",
   "G.GGGGGGGG.G",
   ".GGGGG.GG.G.",
   "G.GGGGGGGGGG",
   ".GGG....GGG.",
   "...........G"
  ],
  "meta": {
   "anchor": [
    5,
    6
   ]
  }
 },
 {
  "name": "canopy_tall",
  "w": 12,
  "h": 16,
  "cat": "tree",
  "kind": "canopy",
  "rows": [
   ".....G.G....",
   "..G.GGG.G...",
   "...GGGGG.G..",
   "...G.GGGG...",
   "..G.GGGGGG..",
   ".G.GGGGGGG..",
   "G.G.GGGGG.G.",
   ".GGGGGGG.G..",
   ".G.GGGGGGG..",
   "..GGGGGGGG.G",
   ".G.G.GGG.GG.",
   "..G...GGG.G.",
   "........GG..",
   "............",
   "...G....G...",
   "..G.G......."
  ],
  "meta": {
   "anchor": [
    4,
    11
   ]
  }
 },
 {
  "name": "castle_gate",
  "w": 19,
  "h": 7,
  "cat": "wall",
  "kind": "sprite",
  "rows": [
   "SSSSSSSSSSSSSSSS.SS",
   "SSSSSSS.....SSSSSSS",
   "SSSSSS.XXXXX.SSSSSS",
   "S.SSSS.X.X.X.SSSSSS",
   "SSSSSS.X.X.X.SSSSSS",
   "SSSSSS.X.X.X.SSSS.S",
   "SSSSSSSXXXXXSSSSSSS"
  ]
 },
 {
  "name": "castle_gate_wide",
  "w": 27,
  "h": 7,
  "cat": "wall",
  "kind": "sprite",
  "rows": [
   "SSSSSSSSSSSSSSSSSSSSSSSS.SS",
   "SSSSSSSSSSS.....SSSSSSSSSSS",
   "SSSSSSSSSS.XXXXX.SSSSSSSSSS",
   "S.SSSSSSSS.X.X.X.SSSSSSSSSS",
   "SSSSSSSSSS.X.X.X.SSSSSSSSSS",
   "SSSSSSSSSS.X.X.X.SSSSSSSS.S",
   "SSSSSSSSSSSXXXXXSSSSSSSSSSS"
  ]
 },
 {
  "name": "castle_top",
  "w": 19,
  "h": 5,
  "cat": "roof",
  "kind": "sprite",
  "rows": [
   "S.S.S.S.S.S.S.S.S.S",
   "SSSSSSSSSSSSSSSSSSS",
   "SSSS.SSSSSSSSS.SSSS",
   "SSSS.SSSSSSSSS.SSSS",
   "SSSSSSSSSSSSSSSSSSS"
  ]
 },
 {
  "name": "castle_top_wide",
  "w": 27,
  "h": 5,
  "cat": "roof",
  "kind": "sprite",
  "rows": [
   "S.S.S.S.S.S.S.S.S.S.S.S.S.S",
   "SSSSSSSSSSSSSSSSSSSSSSSSSSS",
   "SSSSSSSS.SSSSSSSSS.SSSSSSSS",
   "SSSSSSSS.SSSSSSSSS.SSSSSSSS",
   "SSSSSSSSSSSSSSSSSSSSSSSSSSS"
  ]
 },
 {
  "name": "castle_wall",
  "w": 19,
  "h": 6,
  "cat": "upper",
  "kind": "sprite",
  "rows": [
   "SSSSSSSSSSSSSSSSSSS",
   "S.SSSSSSSSSSSSSSSSS",
   "SSSSSSSSS.SSSSSSSSS",
   "SSSSSSSSS.SSSSSSSSS",
   "SSSSSSSSSSSSSSSSS.S",
   "SSSSSSSSSSSSSSSSSSS"
  ]
 },
 {
  "name": "castle_wall_wide",
  "w": 27,
  "h": 6,
  "cat": "upper",
  "kind": "sprite",
  "rows": [
   "SSSSSSSSSSSSSSSSSSSSSSSSSSS",
   "S.SSSSSSSSSSSSSSSSSSSSSSSSS",
   "SSSSSSSSSSSSS.SSSSSSSSSSSSS",
   "SSSSSSSSSSSSS.SSSSSSSSSSSSS",
   "SSSSSSSSSSSSSSSSSSSSSSSSS.S",
   "SSSSSSSSSSSSSSSSSSSSSSSSSSS"
  ]
 },
 {
  "name": "chest",
  "w": 20,
  "h": 15,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "....XXXXXXXXXXXX....",
   "...XXXXXXXXXXXXXXX..",
   "..XXX.XXXXXXXXX.XXX.",
   "..XX..XXXXXXXXX..XX.",
   ".XXXXXXXXXXXXXXXXXXX",
   ".XH...H...HH...H..X.",
   ".X.H.....H..H.....X.",
   "XXXXXXXXXXXXXXXXXXXX",
   "XX..XXXXXX.XXXXX..XX",
   "XX..XXXXX.X.XXXX..XX",
   "XX..XXXXXX.XXXXX..XX",
   "XX..XXXXXXXXXXXX..XX",
   "XX..XXXXXXXXXXXX..XX",
   "XXXXXXXXXXXXXXXXXXXX",
   ".XXXXXXXXXXXXXXXXXX."
  ]
 },
 {
  "name": "crossed_axes",
  "w": 17,
  "h": 17,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "..XXXX.....XXXX..",
   ".XXXXXX...XXXXXX.",
   "XXX.XXXX.XXXX.XXX",
   "XH...XXX.XXX...HX",
   "XX...XXX.XXX...XX",
   ".X..XXX...XXX..X.",
   ".....XXX.XXX.....",
   "......XXXXX......",
   ".......XHX.......",
   "......XX.XX......",
   ".....XX...XX.....",
   "....XX.....XX....",
   "...XH.......HX...",
   "..XX.........XX..",
   ".XX...........XX.",
   "XX.............XX",
   "X...............X"
  ]
 },
 {
  "name": "crossed_beams",
  "w": 9,
  "h": 7,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "...X.X...",
   "....X....",
   "...X.X...",
   "....X....",
   "...X.X...",
   ".XX.X.XX.",
   "X...X...X"
  ]
 },
 {
  "name": "crossed_combo_hammer",
  "w": 17,
  "h": 17,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "...X.......XXXXX.",
   "..XXX.....XXXXX..",
   ".XXHXX....XXXX...",
   "XXXXX....XXHX...X",
   ".XXXX.....XX...XX",
   "..X.XX....XX..XXX",
   ".....XX....X.XXX.",
   "......XX..XX.X...",
   ".......XXXX......",
   "........HX.......",
   ".......XXXX......",
   ".XXXX.XX..XX.....",
   "XXXHXXX....XX....",
   "XX..XX......HX...",
   "XX..XX.......XX..",
   "XXXXXX........XX.",
   ".XXXX..........XX"
  ]
 },
 {
  "name": "crossed_hammer_pick",
  "w": 17,
  "h": 17,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "XXXXXX...........",
   "XXHXXX....XXXXXXX",
   "XXXXXX...XXXXXXXX",
   "XXXXXX..XXXXHXXX.",
   "...XXXX.XXXX.....",
   "....XXX.XXX......",
   ".....XXXXX.......",
   "......XXX........",
   ".......XHX.......",
   "......XX.XX......",
   ".....XX...XX.....",
   "....XX.....XX....",
   "...XH.......HX...",
   "..XX.........XX..",
   ".XX...........XX.",
   "XX.............XX",
   "X...............X"
  ]
 },
 {
  "name": "crossed_hammers",
  "w": 17,
  "h": 17,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "XXXXXX.....XXXXXX",
   "XXHXXX.....XXXHXX",
   "XXXXXX.....XXXXXX",
   "XXXXXX.....XXXXXX",
   "...XXXX...XXXX...",
   "....XXX...XXX....",
   ".....XXX.XXX.....",
   "......XXXXX......",
   ".......XHX.......",
   "......XX.XX......",
   ".....XX...XX.....",
   "....XX.....XX....",
   "...XH.......HX...",
   "..XX.........XX..",
   ".XX...........XX.",
   "XX.............XX",
   "X...............X"
  ]
 },
 {
  "name": "crossed_keys",
  "w": 17,
  "h": 17,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "XXXX.........XXXX",
   "X.XX.........XX.X",
   "X.XXX.......XXX.X",
   "XXXXXX.....XXXXXX",
   "..XXXXX...XXXXX..",
   "...XXXX...XXXX...",
   "....XXX...XXX....",
   ".....XXX.XXX.....",
   "......XXXXX......",
   ".......XHX.......",
   "......XX.XX......",
   ".....XX...XX.....",
   "....XX.....XX....",
   "...XXX.....XXX...",
   "..XXHXX...XXHXX..",
   ".XX...XX.XX...XX.",
   "..XXXXX...XXXXX.."
  ]
 },
 {
  "name": "crossed_pick_shovel",
  "w": 17,
  "h": 17,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "XXXXXXXX....XXXX.",
   "XX...XXXX..XXXXXX",
   "H.....XXX..XXXXXX",
   "......XXX..XXHXXX",
   ".....XXX....XXXX.",
   "....XXX......XX..",
   ".....XXX.XXX.....",
   "......XXXXX......",
   ".......XHX.......",
   "......XX.XX......",
   ".....XX...XX.....",
   "....XX.....XX....",
   "...XH.......HX...",
   "..XX.........XX..",
   ".XX...........XX.",
   "XX.............XX",
   "X...............X"
  ]
 },
 {
  "name": "crossed_saw_chisel",
  "w": 17,
  "h": 17,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "XXXXXXXXX......XX",
   "XXXXXXXXXX....XXX",
   "XHXXXXXXXXX..XXXX",
   "X.X.X.X.XXX..XHXX",
   ".....XXXXXX..XXX.",
   "....XXX.XXX.XXX..",
   ".....XXX.XXX.....",
   "......XXXXX......",
   ".......XHX.......",
   "......XX.XX......",
   ".....XX...XX.....",
   "....XX.....XX....",
   "...XH.......HX...",
   "..XX.........XX..",
   ".XX...........XX.",
   "XX.............XX",
   "X...............X"
  ]
 },
 {
  "name": "crossed_spanners",
  "w": 17,
  "h": 17,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   ".XXXXX.....XXXXX.",
   "..XXXXX...XXXXX..",
   "...XXXX...XXXX...",
   "X...XHXX.XXHX...X",
   "XX...XX...XX...XX",
   "XXX..XX...XX..XXX",
   ".XXX.X.....X.XXX.",
   "...X.XX...XX.X...",
   "......XX.XX......",
   ".......XHX.......",
   ".......XXX.......",
   "......XX.XX......",
   ".....XX...XX.....",
   "....HX.....XH....",
   "...XX.......XX...",
   "..XX.........XX..",
   ".XX...........XX."
  ]
 },
 {
  "name": "crossed_swords",
  "w": 17,
  "h": 17,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   ".X.............X.",
   ".XX...........XX.",
   ".XXX.........XXX.",
   "..XXX.......XXX..",
   "..XHX.......XHX..",
   "...XXX.....XXX...",
   "....XXX...XXX....",
   ".....XXX.XXX.....",
   "......XXXXX......",
   ".......XHX.......",
   "......XX.XX......",
   "....XXXX.XXXX....",
   "...XXXXX.XXXXX...",
   "...X.XX...XX.X...",
   "....XX.....XX....",
   "...XX.......XX...",
   "...XX.......XX..."
  ]
 },
 {
  "name": "crossed_tools",
  "w": 17,
  "h": 17,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "...XX......XXXXX.",
   "..XXXX....XXXXX..",
   ".XXHXX....XXXX...",
   "XXXXX....XXHX...X",
   "XXXXX.....XX...XX",
   ".XX.XX....XX..XXX",
   ".....XX....X.XXX.",
   "......XX..XX.X...",
   ".......XXXX......",
   "........HX.......",
   ".......XXXX......",
   "......XX..XX.....",
   ".....XX....XX....",
   "....HX......HX...",
   "...XX........XX..",
   "..XX..........XX.",
   ".XX............XX"
  ]
 },
 {
  "name": "crossed_wrench_screwdriver",
  "w": 17,
  "h": 17,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   ".XXXXX..........X",
   "..XXXXX........HX",
   "...XXXX........X.",
   "X...XHXX......X..",
   "XX...XX......X...",
   "XXX..XX.....X....",
   ".XXX.X.....X.....",
   "...X.XX...X......",
   "......XXXXX......",
   ".......XHX.......",
   "......XXXX.......",
   ".....XXX.XX......",
   "....XXX...XX.....",
   "...XHX.....XH....",
   "..XXX.......XX...",
   ".XXX.........XX..",
   "XXX...........XX."
  ]
 },
 {
  "name": "crystal_ball",
  "w": 17,
  "h": 18,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   ".......XXX.......",
   ".....XXXXXXX.....",
   "....XXXXXXXXX....",
   "...XXX..XXXXXX...",
   "..XXX..XXXXXXXX..",
   ".XXXX.XXXXXXXXXX.",
   ".XXXXXXXXXXHXXXX.",
   "XXXXXXXXXXXXXXXXX",
   "XXXXXXXXXXXXXXXXX",
   "XXXXHXXXXXXXXXXXX",
   ".XXXXXXXXXXXXXXX.",
   ".XXXXXXXXXHXXXXX.",
   "..XXXXXXXXXXXXX..",
   "...XXXXXXXXXXX...",
   ".....XXXXXXX.....",
   "...XXX.....XXX...",
   "..XXXXXXXXXXXXX..",
   ".XXXXXXXXXXXXXXX."
  ]
 },
 {
  "name": "fence_1",
  "w": 15,
  "h": 6,
  "cat": "fence",
  "kind": "sprite",
  "rows": [
   "X.......X......",
   "X.X.X.X.X......",
   "X..X.X..X......",
   "X.X.X.X.X......",
   "X..X.X..X......",
   "X.X.X.X.X......"
  ]
 },
 {
  "name": "fence_2",
  "w": 9,
  "h": 6,
  "cat": "fence",
  "kind": "sprite",
  "rows": [
   "X.X.X.X.X",
   "XXXXXXXXX",
   "X.X.X.X.X",
   "X.X.X.X.X",
   "XXXXXXXXX",
   "X.X.X.X.X"
  ]
 },
 {
  "name": "fence_3",
  "w": 8,
  "h": 6,
  "cat": "fence",
  "kind": "sprite",
  "rows": [
   "X.X..X.X",
   "XXXXXXXX",
   "X.X..X.X",
   "X.X.X..X",
   "XXXXXXXX",
   "X.X.X..X"
  ]
 },
 {
  "name": "fence_4",
  "w": 9,
  "h": 6,
  "cat": "fence",
  "kind": "sprite",
  "rows": [
   "X.X.X...X",
   "XXXXXXXXX",
   "X.X.X.X.X",
   "X...X.X.X",
   "XXXXXXXXX",
   "X.X.X.X.X"
  ]
 },
 {
  "name": "flowers",
  "w": 7,
  "h": 5,
  "cat": "ground",
  "kind": "sprite",
  "rows": [
   "X...X..",
   "XX.XXX.",
   ".X..X.X",
   ".X..X.X",
   "XXXXXXX"
  ]
 },
 {
  "name": "forge_base",
  "w": 23,
  "h": 7,
  "cat": "wall",
  "kind": "sprite",
  "rows": [
   "XXXXXXXXXXXXXXXXXXXXXXX",
   "X.......X.X.XXX.X.X...X",
   "X.......X.XX.X.XX.X...X",
   "X..XXX..X.XXX.XXX.X...X",
   "X...X...X.XX.X.XX.XXXXX",
   "X..XXX..X.X.XXX.X.XX.XX",
   "XXXXXXXXXXXXXXXXXXXXXXX"
  ]
 },
 {
  "name": "grass_1",
  "w": 2,
  "h": 2,
  "cat": "ground",
  "kind": "sprite",
  "rows": [
   "G.",
   ".G"
  ]
 },
 {
  "name": "grass_2",
  "w": 2,
  "h": 3,
  "cat": "ground",
  "kind": "sprite",
  "rows": [
   ".G",
   "G.",
   "G."
  ]
 },
 {
  "name": "grass_3",
  "w": 2,
  "h": 3,
  "cat": "ground",
  "kind": "sprite",
  "rows": [
   ".G",
   "G.",
   "G."
  ]
 },
 {
  "name": "grass_4",
  "w": 7,
  "h": 3,
  "cat": "ground",
  "kind": "sprite",
  "rows": [
   "G..G..G",
   ".G.G.G.",
   ".G.G.G."
  ]
 },
 {
  "name": "grass_5",
  "w": 9,
  "h": 3,
  "cat": "ground",
  "kind": "sprite",
  "rows": [
   "G..G.G..G",
   ".GG.GG.G.",
   ".G..G..G."
  ]
 },
 {
  "name": "hammer",
  "w": 15,
  "h": 15,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "...XX..........",
   "..XXXX.........",
   ".XXHXX.........",
   "XXXXX..........",
   "XXXXX..........",
   ".XX.XX.........",
   ".....XX........",
   "......HX.......",
   ".......XX......",
   "........XX.....",
   ".........XX....",
   "..........HX...",
   "...........XX..",
   "............XX.",
   ".............XX"
  ]
 },
 {
  "name": "hammer_ball_peen",
  "w": 21,
  "h": 21,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   ".XXX.................",
   "XXXXX................",
   "XXXXXX...............",
   "XXXXXX...............",
   ".XXXX................",
   "..XX.................",
   ".....XX..............",
   "......XX.............",
   ".......XX............",
   "........XX...........",
   ".........XX..........",
   "..........XX.........",
   "...........XX........",
   "............XX.......",
   ".............XX......",
   "..............XX.....",
   "...............XX....",
   "................XX...",
   ".................XX..",
   "..................XX.",
   "...................XX"
  ]
 },
 {
  "name": "hammer_claw",
  "w": 21,
  "h": 21,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "....XX...XX..........",
   "....XXX..X...........",
   "...XXXXX.............",
   "..XXXXX..............",
   ".XXXXX...............",
   "XXXXX................",
   ".XXX.XX..............",
   "..X...XX.............",
   ".......XX............",
   "........XX...........",
   ".........XX..........",
   "..........XX.........",
   "...........XX........",
   "............XX.......",
   ".............XX......",
   "..............XX.....",
   "...............XX....",
   "................XX...",
   ".................XX..",
   "..................XX.",
   "...................XX"
  ]
 },
 {
  "name": "hammer_cross_peen",
  "w": 21,
  "h": 21,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "...XX................",
   "..XXX................",
   ".XXXXX...............",
   "XXXXXX...............",
   "XXXXX................",
   "..XX.................",
   ".....XX..............",
   "......XX.............",
   ".......XX............",
   "........XX...........",
   ".........XX..........",
   "..........XX.........",
   "...........XX........",
   "............XX.......",
   ".............XX......",
   "..............XX.....",
   "...............XX....",
   "................XX...",
   ".................XX..",
   "..................XX.",
   "...................XX"
  ]
 },
 {
  "name": "hammer_gavel",
  "w": 21,
  "h": 21,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "....XXXX.............",
   "...XXXXX.............",
   "..XXXXXX.............",
   ".XXXXXXX.............",
   "XXXXXXX..............",
   "XXXXXX...............",
   "XXXXX................",
   "XXXX..XX.............",
   ".......XX............",
   "........XX...........",
   ".........XX..........",
   "..........XX.........",
   "...........XX........",
   "............XX.......",
   ".............XX......",
   "..............XX.....",
   "........XXXXXXXXXXXX.",
   "........XXXXXXXXXXXX.",
   "........X..........X.",
   "........XXXXXXXXXXXX.",
   "...................XX"
  ]
 },
 {
  "name": "hammer_icon",
  "w": 18,
  "h": 17,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "......XHXHXX......",
   ".....XXHXXXHX.....",
   ".....XX...XXHX....",
   "...........XXXX...",
   "..........XHXHXX..",
   ".........X.XXXXX..",
   "........XXX.XXXXHX",
   ".......XXXX...XHXH",
   "......XXXXH....XX.",
   ".....XXHXX........",
   "....XXXXH.........",
   "...XXHXX..........",
   "..XXXXH...........",
   ".XXHXX............",
   "XXXXH.............",
   "XXHX..............",
   ".XX..............."
  ]
 },
 {
  "name": "hammer_mallet",
  "w": 21,
  "h": 21,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "....XXXX.............",
   "...XXXXX.............",
   "..XXXXXX.............",
   ".XXXXXXX.............",
   "XXXXXXX..............",
   "XXXXXX...............",
   "XXXXX................",
   "XXXX..XX.............",
   ".......XX............",
   "........XX...........",
   ".........XX..........",
   "..........XX.........",
   "...........XX........",
   "............XX.......",
   ".............XX......",
   "..............XX.....",
   "...............XX....",
   "................XX...",
   ".................XX..",
   "..................XX.",
   "...................XX"
  ]
 },
 {
  "name": "hammer_sledge",
  "w": 21,
  "h": 21,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "...XXX...............",
   "..XXXXX..............",
   ".XXXXXXX.............",
   "XXXXXXXXX............",
   "XXXXXXXX.............",
   "XXXXXXX..............",
   ".XXXXXX..............",
   "..XXX.XX.............",
   "...X...XX............",
   "........XX...........",
   ".........XX..........",
   "..........XX.........",
   "...........XX........",
   "............XX.......",
   ".............XX......",
   "..............XX.....",
   "...............XX....",
   "................XX...",
   ".................XX..",
   "..................XX.",
   "...................XX"
  ]
 },
 {
  "name": "hammer_upright",
  "w": 13,
  "h": 16,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "XXXXXXXXXXXXX",
   "XX.XXXXXXX.XX",
   "XXXXXXXXXXXXX",
   "XXXXXXXXXXXXX",
   "XX.XXXXXXX.XX",
   "XXXXXXXXXXXXX",
   ".....XXX.....",
   ".....XXX.....",
   ".....XXX.....",
   ".....XXX.....",
   ".....XXX.....",
   ".....XXX.....",
   ".....XXX.....",
   ".....XXX.....",
   ".....XXX.....",
   ".....XXX....."
  ]
 },
 {
  "name": "hammer_war_hammer",
  "w": 21,
  "h": 19,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "..XX.X...............",
   ".XX.XXX..............",
   ".X.XXXXX.............",
   "X.XXXXXXX............",
   ".XXXXXXX.............",
   "..XXXXX..............",
   "...XXX...............",
   "....X..XXX...........",
   "........XXX..........",
   ".........XXX.........",
   "..........XXX........",
   "...........XXX.......",
   "............XXX......",
   ".............XXX.....",
   "..............XXX....",
   "...............XXX...",
   "................XXX..",
   ".................XXX.",
   "..................XXX"
  ]
 },
 {
  "name": "hedge",
  "w": 17,
  "h": 5,
  "cat": "tree",
  "kind": "sprite",
  "rows": [
   "..G.G..G.G..G.G..",
   ".GGGGG.GGGG.GGGG.",
   "GGGG.GGGGGGGGG.GG",
   ".GGGGGGG.GGGGGGG.",
   "..GGGGGGGGGGGGG.."
  ]
 },
 {
  "name": "inkpot",
  "w": 13,
  "h": 15,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "..........XX.",
   ".........X.X.",
   "........X.XX.",
   ".......X.XX..",
   "......X.XX...",
   "......XXX....",
   ".....XX......",
   ".....X.......",
   "...XXXXXXX...",
   "..X.......X..",
   "..XXXXXXXXX..",
   ".XX.......XX.",
   ".X.........X.",
   ".X.........X.",
   "..XXXXXXXXX.."
  ]
 },
 {
  "name": "lamp_post",
  "w": 6,
  "h": 15,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "..X...",
   ".X.X..",
   "..X...",
   "..X...",
   ".XXX..",
   "XXXXX.",
   "......",
   ".X.X..",
   ".X.X..",
   ".XXX..",
   ".X.X..",
   ".XXX..",
   ".XXX..",
   ".XXX..",
   "XXXXX."
  ]
 },
 {
  "name": "letter",
  "w": 17,
  "h": 11,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "XXXXXXXXXXXXXXXXX",
   "XX.............XX",
   "X.X...........X.X",
   "X..X.........X..X",
   "X...X.......X...X",
   "X....X.....X....X",
   "X.....X.XX......X",
   "X......XXX......X",
   "X.......X.......X",
   "X...............X",
   "XXXXXXXXXXXXXXXXX"
  ]
 },
 {
  "name": "log",
  "w": 9,
  "h": 3,
  "cat": "ground",
  "kind": "sprite",
  "rows": [
   "XXXXXXXX.",
   "X.XXXXXXX",
   "XXXXXXXX."
  ]
 },
 {
  "name": "marker",
  "w": 5,
  "h": 6,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "..S..",
   ".S.S.",
   "..S..",
   "..S..",
   ".S.S.",
   "SSSSS"
  ]
 },
 {
  "name": "mushroom",
  "w": 5,
  "h": 5,
  "cat": "ground",
  "kind": "sprite",
  "rows": [
   ".XXX.",
   "XX.XX",
   "..X..",
   "..X..",
   ".XXX."
  ]
 },
 {
  "name": "mushrooms",
  "w": 9,
  "h": 5,
  "cat": "ground",
  "kind": "sprite",
  "rows": [
   ".XXX.....",
   "XX.XX.XX.",
   "..X..X.X.",
   "..X...X..",
   ".XXX.XXX."
  ]
 },
 {
  "name": "notice_board",
  "w": 13,
  "h": 14,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "......X......",
   ".....XXX.....",
   "....XXXXX....",
   "...XXX.XXX...",
   "..XXXXXXXXX..",
   ".XXXXXXXXXXX.",
   ".X.........X.",
   ".X.XXX.XXX.X.",
   ".X.........X.",
   ".X.XXXXX.X.X.",
   ".X.........X.",
   ".XXXXXXXXXXX.",
   "..X.......X..",
   "..X.......X.."
  ]
 },
 {
  "name": "observatory_top",
  "w": 13,
  "h": 8,
  "cat": "roof",
  "kind": "sprite",
  "rows": [
   "..........X..",
   ".........X...",
   "....XXXXX....",
   "..XXXXX.XX...",
   ".XXXXXX.XXXX.",
   ".XXXXXXXXXXX.",
   "XXXXXXXXXXXXX",
   "X.XXXXXXXXX.X"
  ]
 },
 {
  "name": "pencil",
  "w": 18,
  "h": 18,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "................XX",
   "..............X.XX",
   ".............XX.XX",
   "............XXX.X.",
   "...........XXXX...",
   "..........XX.XX...",
   ".........XX.XX....",
   "........XX.XX.....",
   ".......XX.XX......",
   "......XX.XX.......",
   ".....XX.XX........",
   "....XX.XX.........",
   "....XXXX..........",
   "...XXXX...........",
   "..XXXX............",
   "..XXX.............",
   ".X................",
   "X................."
  ]
 },
 {
  "name": "quill",
  "w": 16,
  "h": 16,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "..........XXX...",
   "........XXXXXXX.",
   ".......XXXXHXXXX",
   "......XXXXXXXXXX",
   ".....XXXHXXXXXX.",
   ".....XXXXXXXX...",
   "....XX.XXHXX....",
   "....X.XXXXX.....",
   "...X.XHXXX......",
   "...X.XXX........",
   "..X.XX..........",
   "..XXX...........",
   "..XX............",
   ".X..............",
   ".X..............",
   "X..............."
  ]
 },
 {
  "name": "rock",
  "w": 5,
  "h": 3,
  "cat": "ground",
  "kind": "sprite",
  "rows": [
   ".XXX.",
   "XXXXX",
   "XX.XX"
  ]
 },
 {
  "name": "rocks",
  "w": 9,
  "h": 4,
  "cat": "ground",
  "kind": "sprite",
  "rows": [
   "....XX...",
   ".XX.XXXX.",
   "XXXXXX.XX",
   "XX.XXXXXX"
  ]
 },
 {
  "name": "roof_1",
  "w": 15,
  "h": 8,
  "cat": "roof",
  "kind": "sprite",
  "rows": [
   ".......X.......",
   "......XXX......",
   ".....X.XXX.....",
   "....XXXXXXX....",
   "...XXXXXXX.X...",
   "..XXXXXXXXX.X..",
   ".XXX.XXXXXXXXX.",
   "XXX.XXXXXXXX.XX"
  ]
 },
 {
  "name": "roof_2",
  "w": 19,
  "h": 10,
  "cat": "roof",
  "kind": "sprite",
  "rows": [
   ".........X.........",
   "........XXX........",
   ".......XX.XX.......",
   "......XXXXXXX......",
   ".....XX.X.X.XX.....",
   "....X.X.....X.X....",
   "...XX.X.....X.XX...",
   "..X.X.X.....X.X.X..",
   ".X...............X.",
   "X.................X"
  ]
 },
 {
  "name": "roof_3",
  "w": 19,
  "h": 10,
  "cat": "roof",
  "kind": "sprite",
  "rows": [
   ".........X.........",
   "........XXX........",
   ".......XX.XX.......",
   "......X.X.X.X......",
   ".....XX.X.X.XX.....",
   "....X.XXX.X.X.X....",
   "...XX.X.X.XXX.XX...",
   "..X.X.X.X.X.X.X.X..",
   ".X...............X.",
   "X.................X"
  ]
 },
 {
  "name": "roof_4",
  "w": 19,
  "h": 10,
  "cat": "roof",
  "kind": "sprite",
  "rows": [
   ".........X.........",
   "........X.X........",
   ".......X.W.X.......",
   "......X.WWW.X......",
   ".....X.WW.WW.X.....",
   "....X.W.WWW.W.X....",
   "...X.WWW.W.WWW.X...",
   "..X.WWWWW.WWWWW.X..",
   ".X...............X.",
   "X.................X"
  ]
 },
 {
  "name": "roof_5",
  "w": 25,
  "h": 8,
  "cat": "roof",
  "kind": "sprite",
  "rows": [
   "...XXXXXXXXXXXXXXXXXXX...",
   "...X.X.XXXXXXXXXXXXX.X...",
   "..XXX.HXXXXXXXXXXXHXXXX..",
   "..XX.XXXXXXXHXX.XXXXXXX..",
   ".XXXXXX.X.XXXX.X.X.XXXXX.",
   ".XXXXXXX.HXXXXX.X.XXHXXX.",
   "XXXX.XXXXXXXXXXXXXXXXXXXX",
   "XXXXXXXXXXXXXXXXXXXXXXXXX"
  ]
 },
 {
  "name": "roof_6",
  "w": 29,
  "h": 11,
  "cat": "roof",
  "kind": "sprite",
  "rows": [
   "XX...........................",
   "..XXXXXXX....................",
   "...XXXX..XXXXXXX.............",
   "..XXXXXXXXXX.X..XXXXXXXXXXX..",
   "..XXXXXXXXXXXXXXXXXXXXXXXX.X.",
   "...XXXXXXXXXXXXXXXXXXXXXXXXX.",
   "...XXXXXXXXXXXXXXXXXXXXXXXXX.",
   "...X.XXXXXXXX.XXXXXXXXXXXXXX.",
   "....X.XXXXXX.XXXXXXXXXXXXXXXX",
   "....XXXXXXXXXXXXXXXXXXXX.XXXX",
   "....XXXXXXXXXXXXXXXX.XXXXXXXX"
  ]
 },
 {
  "name": "roof_7",
  "w": 25,
  "h": 8,
  "cat": "roof",
  "kind": "sprite",
  "rows": [
   "...XXXXXXXXXXXXX.XXXXXXXX",
   "...X.X.XXXXXXXXXXXXXXXXX.",
   "..XXX.XXXXXXXXXXXXXX.XX..",
   "..XX.XXXXXXXXXXXXXX.XX...",
   ".XXXXXXXXXXXXXXXXXXXX....",
   ".XXXXXXXXXXXXX.XXXXX.....",
   "XXXX.XX.XXXXXXX.XXX......",
   "XXXXXXXXXXXXXXXXXX......."
  ]
 },
 {
  "name": "roof_tower",
  "w": 11,
  "h": 6,
  "cat": "roof",
  "kind": "sprite",
  "rows": [
   ".....X.....",
   "....XXX....",
   "...XXXXX...",
   "..XXX.XXX..",
   ".XXXXXXXXX.",
   "XXXXXXX.XXX"
  ]
 },
 {
  "name": "scroll",
  "w": 17,
  "h": 13,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "XX.............XX",
   "X.X...........X.X",
   "XXXXXXXXXXXXXXXXX",
   "XX.............XX",
   "XX..XXXXXXXXX..XX",
   "XX.............XX",
   "XX..XXXXXX.....XX",
   "XX.............XX",
   "XX..XXXXXXXX...XX",
   "XX.............XX",
   "XXXXXXXXXXXXXXXXX",
   "X.X...........X.X",
   "XX.............XX"
  ]
 },
 {
  "name": "shrub",
  "w": 7,
  "h": 4,
  "cat": "tree",
  "kind": "sprite",
  "rows": [
   "..G.G..",
   ".GGGGG.",
   "G.GGG.G",
   ".GG.GG."
  ]
 },
 {
  "name": "signpost",
  "w": 9,
  "h": 9,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "XXXXXXX..",
   ".X.X.X...",
   ".X...XX..",
   ".X.X.X.XX",
   ".........",
   "SSSSSSS..",
   ".S.S.S...",
   ".SS.SS...",
   "SSSSSSS.."
  ]
 },
 {
  "name": "skull",
  "w": 16,
  "h": 19,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   ".....XXXXXX.....",
   "...XXXXXXXXXX...",
   "..XXXXXXXXXXXX..",
   ".XXXXXXXXXX.XXX.",
   ".XXXXXXXXXXX.XX.",
   "XXXXXXXXXXXXX.XX",
   "XXXXXXXXXXXXXXXX",
   "XXX....XXX....XX",
   "XX......X......X",
   "XX......X......X",
   "XXX....XXX....XX",
   ".XXXXXXXXXXXXXX.",
   ".XXXXXX..XXXXXX.",
   "..XXXXX..XXXXX..",
   "..XXXXXXXXXXXX..",
   "...X.X.X.X.X.X..",
   "...X.X.X.X.X.X..",
   "....XXXXXXXXXX..",
   ".....XXXXXXXX..."
  ]
 },
 {
  "name": "stone_1",
  "w": 11,
  "h": 7,
  "cat": "stone",
  "kind": "sprite",
  "rows": [
   "SSSSSSSSSSS",
   ".SS.....SS.",
   "SSSSSSSSSSS",
   "S.SS...SSSS",
   "SS.S...SS.S",
   ".SSS...SSS.",
   "SSSS...SSSS"
  ]
 },
 {
  "name": "stone_2",
  "w": 15,
  "h": 7,
  "cat": "stone",
  "kind": "sprite",
  "rows": [
   "SSSS.SSSSSSSSSS",
   ".SSSSSS.S.SSSS.",
   "SS..SS.X.SS..SS",
   "SS..SS.X.SS..SS",
   ".SSSS.X.X.SSSSS",
   "S.SSS.XXX.SSS..",
   "SSSSS.XXX.SSSSS"
  ]
 },
 {
  "name": "stone_3",
  "w": 19,
  "h": 7,
  "cat": "stone",
  "kind": "sprite",
  "rows": [
   "SSSSSSSSSSSSSSSSSSS",
   "..SSSSS.....SSSSSS.",
   "SSSS..SSSSSSS..SSSS",
   "S.SS..SS...SS..S..S",
   "SS.SSSSS...SSSS.SSS",
   ".SSSSSSS...SSSSSS..",
   "SSSSSSSS...SSSSSSSS"
  ]
 },
 {
  "name": "stone_gate",
  "w": 13,
  "h": 7,
  "cat": "stone",
  "kind": "sprite",
  "rows": [
   "SSSSSSSS..SSS",
   "..SSS.S..SSSS",
   "SSSS.S..S.SSS",
   ".SS.S..SSSSSS",
   "S.SS..S.SSSSS",
   "SSS..S.SSSSS.",
   "SS..SSSSSSSSS"
  ]
 },
 {
  "name": "stone_ground",
  "w": 10,
  "h": 3,
  "cat": "stone",
  "kind": "sprite",
  "rows": [
   "SS.SSSSSSS",
   ".SSSSS.SS.",
   "SSSSS.SSSS"
  ]
 },
 {
  "name": "stone_tower",
  "w": 11,
  "h": 18,
  "cat": "stone",
  "kind": "sprite",
  "rows": [
   ".SSSSSSSSSS",
   "SSSSSSSSSSS",
   "SSSSSSSSSSS",
   "SSSSS.SSSSS",
   "SSSSS.SSSSS",
   "SSSSSSSS.SS",
   "SSSSSSSSS.S",
   "SSSSSSSSSSS",
   "SSSSSSSSSSS",
   "SSSSS.SSSSS",
   "SSSSS.SSSSS",
   "SSSSSSSSSSS",
   "SSSSSSSSSSS",
   "S.SSSSSSSSS",
   ".SSSSSSSSSS",
   "SSSSS.SSSSS",
   "SSSSS.SSSSS",
   "SSSSSSSSSSS"
  ]
 },
 {
  "name": "sword",
  "w": 11,
  "h": 22,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   ".....X.....",
   "....XHX....",
   "....XHX....",
   "....XHX....",
   "....XHX....",
   "....XHX....",
   "....XHX....",
   "....XHX....",
   "....XHX....",
   "....XHX....",
   "....XHX....",
   "....XHX....",
   ".XXXXXXXXX.",
   "XXXXXXXXXXX",
   "....XXX....",
   "....X.X....",
   "....XXX....",
   "....X.X....",
   "....XXX....",
   "...XXXXX...",
   "..XXXHXXX..",
   "...XXXXX..."
  ]
 },
 {
  "name": "tent",
  "w": 13,
  "h": 9,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "......X......",
   ".....XXX.....",
   "....XXXXX....",
   "...XXX.XXX...",
   "..XXXXXXXXX..",
   ".XXXX...XXXX.",
   "XXXX..X..XXXX",
   "XXXX..X..XX.X",
   "XXXXX.X.XXXXX"
  ]
 },
 {
  "name": "tool_1",
  "w": 7,
  "h": 10,
  "cat": "tool",
  "kind": "sprite",
  "rows": [
   "......X",
   "....XX.",
   "..XX...",
   "XX...X.",
   ".X....X",
   ".X.....",
   ".X.....",
   ".X.....",
   ".X.....",
   ".X....."
  ]
 },
 {
  "name": "tool_2",
  "w": 4,
  "h": 4,
  "cat": "tool",
  "kind": "sprite",
  "rows": [
   "XXXX",
   ".X.X",
   ".XXX",
   "..X."
  ]
 },
 {
  "name": "tool_3",
  "w": 3,
  "h": 5,
  "cat": "tool",
  "kind": "sprite",
  "rows": [
   "SSS",
   ".SS",
   "..S",
   "..S",
   "..S"
  ]
 },
 {
  "name": "tool_4",
  "w": 2,
  "h": 6,
  "cat": "tool",
  "kind": "sprite",
  "rows": [
   "SS",
   ".S",
   "S.",
   "SS",
   "SS",
   "S."
  ]
 },
 {
  "name": "tool_5",
  "w": 7,
  "h": 4,
  "cat": "tool",
  "kind": "sprite",
  "rows": [
   "S......",
   "SSS....",
   "S.SSS..",
   "SS.S.SS"
  ]
 },
 {
  "name": "toolbox",
  "w": 20,
  "h": 14,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   ".......XXXXX........",
   "......XX...XX.......",
   "..XXX.X.....X..XX...",
   "..XXX.X.....X.X.X...",
   "...X..X.....X.X.X...",
   "...X.XXXXXXXXXX.X...",
   "...X.X..........X...",
   "XXXXXXXXXXXXXXXXXXXX",
   "X.HXXXXXXXXHXXXXXXHX",
   "X.XXXX.XXXXXXX.XXXXX",
   "X.XXXX.XXXXXXX.XXXXX",
   "X.XXXX.XXXXXXX.XXXXX",
   "X.XXXXXXXXXXXXXXXXXX",
   "XXXXXXXXXXXXXXXXXXXX"
  ]
 },
 {
  "name": "tower_base",
  "w": 11,
  "h": 7,
  "cat": "wall",
  "kind": "sprite",
  "rows": [
   "S.SSSSSSSSS",
   ".SSSSSSSSSS",
   "SSSS...SSSS",
   "SSS.XXX.SSS",
   "SSS.XXX.SSS",
   "SSS.XXX.SSS",
   "SSSSXXXSSSS"
  ]
 },
 {
  "name": "tower_mid",
  "w": 11,
  "h": 6,
  "cat": "upper",
  "kind": "sprite",
  "rows": [
   "SSSSSSSSSSS",
   "SSSSSSSSSSS",
   "SSSSS.SSSSS",
   "SSSSS.SSSSS",
   "SSSSSSSS.SS",
   "SSSSSSSSS.S"
  ]
 },
 {
  "name": "tower_mid_plain",
  "w": 11,
  "h": 6,
  "cat": "upper",
  "kind": "sprite",
  "rows": [
   "SSSSSSSSSSS",
   "S.SSSSSSSSS",
   ".SSSSSSSSSS",
   "SSSSSSSSSSS",
   "SSSSSSSSS.S",
   "SSSSSSSSSSS"
  ]
 },
 {
  "name": "tower_mid_wide",
  "w": 11,
  "h": 6,
  "cat": "upper",
  "kind": "sprite",
  "rows": [
   "SSSSSSSSSSS",
   "SSS.SSS.SSS",
   "SSS.SSS.SSS",
   "SSSSSSSSSSS",
   "S.SSSSSSSSS",
   "SSSSSSSSSSS"
  ]
 },
 {
  "name": "trunk_gnarled",
  "w": 8,
  "h": 14,
  "cat": "tree",
  "kind": "trunk",
  "rows": [
   "..X.....",
   "X.X..X.X",
   ".X..X..X",
   ".X..X.X.",
   "..XXX.X.",
   ".XXXXX..",
   ".XXX.XX.",
   ".XXXX.X.",
   "..XXXXX.",
   "..XXXXX.",
   "..XXXX..",
   "...XX...",
   "...XXX..",
   "X.XXXXX."
  ],
  "meta": {
   "top": 2,
   "stretch": 11
  }
 },
 {
  "name": "trunk_oak",
  "w": 13,
  "h": 13,
  "cat": "tree",
  "kind": "trunk",
  "rows": [
   "....X.X......",
   ".X...XX...X..",
   "..X..XX..X...",
   "..XX.X.XXX...",
   "...XXXXXX....",
   "...XXXXX.....",
   "...XXX.X.....",
   "...XXX.X.....",
   "...XXXX.X....",
   "..XXXXXXX....",
   "..XX.XXXX....",
   ".XX.XXXXXX...",
   "XXX.XXXXXXX.X"
  ],
  "meta": {
   "top": 5,
   "stretch": 7
  }
 },
 {
  "name": "trunk_round",
  "w": 8,
  "h": 6,
  "cat": "tree",
  "kind": "trunk",
  "rows": [
   "...X....",
   "X...X.X.",
   ".XX..X..",
   "...X.X.X",
   "....X...",
   "....X..."
  ],
  "meta": {
   "top": 3,
   "stretch": 4
  }
 },
 {
  "name": "trunk_stick",
  "w": 1,
  "h": 6,
  "cat": "tree",
  "kind": "trunk",
  "rows": [
   "X",
   "X",
   "X",
   "X",
   "X",
   "X"
  ],
  "meta": {
   "top": 0,
   "stretch": 3
  }
 },
 {
  "name": "trunk_stump",
  "w": 3,
  "h": 10,
  "cat": "tree",
  "kind": "trunk",
  "rows": [
   ".X.",
   ".X.",
   ".X.",
   ".X.",
   ".X.",
   ".X.",
   ".X.",
   ".X.",
   ".X.",
   "X.X"
  ],
  "meta": {
   "top": 1,
   "stretch": 5
  }
 },
 {
  "name": "trunk_tall",
  "w": 4,
  "h": 10,
  "cat": "tree",
  "kind": "trunk",
  "rows": [
   "X...",
   ".X..",
   ".X.X",
   "..X.",
   "..X.",
   ".XX.",
   "..X.",
   "..X.",
   "..X.",
   "..X."
  ],
  "meta": {
   "top": 0,
   "stretch": 8
  }
 },
 {
  "name": "tuft",
  "w": 5,
  "h": 3,
  "cat": "ground",
  "kind": "sprite",
  "rows": [
   ".G.G.",
   ".G.G.",
   "G.G.G"
  ]
 },
 {
  "name": "upper_4",
  "w": 15,
  "h": 6,
  "cat": "upper",
  "kind": "sprite",
  "rows": [
   "W.W.W.W.W.W.W.W",
   "WWWWW.WWW.WWWWW",
   "W.WWW.W.W.WWW.W",
   "WW.WW.WWW.WW.WW",
   "WWW.W.W.W.W.WWW",
   "WWWWWWWWWWWWWWW"
  ]
 },
 {
  "name": "upper_4_inv",
  "w": 15,
  "h": 6,
  "cat": "upper",
  "kind": "sprite",
  "rows": [
   ".X.X.X.X.X.X.X.",
   ".....X...X.....",
   ".X...X.X.X...X.",
   "..X..X...X..X..",
   "...X.X.X.X.X...",
   "..............."
  ]
 },
 {
  "name": "upper_5",
  "w": 17,
  "h": 6,
  "cat": "upper",
  "kind": "sprite",
  "rows": [
   "W.W.W.WWWWW.W.W.W",
   "WWWWW.WW.WW.WWWWW",
   "W.WWW.W...W.WWW.W",
   "WW.WW.W...W.WW.WW",
   "WWW.W.W...W.W.WWW",
   "WWWWWWWWWWWWWWWWW"
  ]
 },
 {
  "name": "upper_5_inv",
  "w": 17,
  "h": 6,
  "cat": "upper",
  "kind": "sprite",
  "rows": [
   ".X.X.X.....X.X.X.",
   ".....X..X..X.....",
   ".X...X.XXX.X...X.",
   "..X..X.XXX.X..X..",
   "...X.X.XXX.X.X...",
   "................."
  ]
 },
 {
  "name": "upper_6",
  "w": 17,
  "h": 6,
  "cat": "upper",
  "kind": "sprite",
  "rows": [
   "W.W.W.W.W.W.W.W.W",
   "WWWWW.WWWWWWWWWWW",
   "W.WWW.WW...W...WW",
   "WW.WW.WW...W...WW",
   "WWW.W.WW...W...WW",
   "WWWWWWWWWWWWWWWWW"
  ]
 },
 {
  "name": "upper_6_inv",
  "w": 17,
  "h": 6,
  "cat": "upper",
  "kind": "sprite",
  "rows": [
   ".X.X.X.X.X.X.X.X.",
   ".....X...........",
   ".X...X..XXX.XXX..",
   "..X..X..XXX.XXX..",
   "...X.X..XXX.XXX..",
   "................."
  ]
 },
 {
  "name": "upper_7",
  "w": 23,
  "h": 6,
  "cat": "upper",
  "kind": "sprite",
  "rows": [
   "W.W.W.W.W.W.W.W.W.W.W.W",
   "WWWWW.WWWWWWWWWWW.WWWWW",
   "W.WWW.WW...W...WW.WWW.W",
   "WW.WW.WW...W...WW.WW.WW",
   "WWW.W.WW...W...WW.W.WWW",
   "WWWWWWWWWWWWWWWWWWWWWWW"
  ]
 },
 {
  "name": "upper_7_inv",
  "w": 23,
  "h": 6,
  "cat": "upper",
  "kind": "sprite",
  "rows": [
   ".X.X.X.X.X.X.X.X.X.X.X.",
   ".....X...........X.....",
   ".X...X..XXX.XXX..X...X.",
   "..X..X..XXX.XXX..X..X..",
   "...X.X..XXX.XXX..X.X...",
   "......................."
  ]
 },
 {
  "name": "wagon",
  "w": 21,
  "h": 14,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "......SSSSSSSSSSSSSSS",
   ".......S.S.S.S.S.S.S.",
   ".....................",
   ".......X...........X.",
   ".......X...........X.",
   ".......X.X.X...X...X.",
   ".....................",
   ".......XXXXXXXXXXXXX.",
   "....XX...X.......X...",
   "...X...XX..XXXXX..XX.",
   "..X...X..X.......X..X",
   ".X....X..X.......X..X",
   "X......XX.........XX.",
   "....................."
  ]
 },
 {
  "name": "wall_1",
  "w": 15,
  "h": 7,
  "cat": "wall",
  "kind": "sprite",
  "rows": [
   "XXXXXXXXXXXXXXX",
   "X.X.X...X...X.X",
   "X.XXX...X...X.X",
   "X.X.X.X.XXXXX.X",
   "XXX.X...X.X.XXX",
   "X.X.X...X.X.X.X",
   "XXXXXXXXXXXXXXX"
  ]
 },
 {
  "name": "wall_2",
  "w": 15,
  "h": 7,
  "cat": "wall",
  "kind": "sprite",
  "rows": [
   "XXXXXXXXXXXXXXX",
   "X.X.X.X.X.X.X.X",
   "XXX.X.X.X.X.X.X",
   "X.X.X.XXX.X.X.X",
   "X.XXX.X.X.X.XXX",
   "X.X.X.X.X.X.X.X",
   ".XXXXXXXXXXXXX."
  ]
 },
 {
  "name": "wall_3",
  "w": 23,
  "h": 7,
  "cat": "wall",
  "kind": "sprite",
  "rows": [
   "XXXXXXXXXXXXXXXXXXXXXXX",
   "X.X...X.X.XXX.X.X...X.X",
   "X.X...X.XX.X.XX.X...X.X",
   "X.X...X.XXX.XXX.X...X.X",
   "X.XXXXX.XX.X.XX.XXXXX.X",
   "X.XX.XX.X.XXX.X.XX.XX.X",
   "XXXXXXXXXXXXXXXXXXXXXXX"
  ]
 },
 {
  "name": "wall_4",
  "w": 15,
  "h": 7,
  "cat": "wall",
  "kind": "sprite",
  "rows": [
   "XXXXXXXXXXXXXXX",
   "X.............X",
   "XXXXXXXXXXXXXXX",
   "X.X.X.XXX.X.X.X",
   "XX.XX.X.X.XX.XX",
   "X.X.X.XXX.X.X.X",
   "XXXXXXXXXXXXXXX"
  ]
 },
 {
  "name": "wall_5",
  "w": 17,
  "h": 7,
  "cat": "wall",
  "kind": "sprite",
  "rows": [
   "XXXXXXXXXXXXXXXXX",
   "X...............X",
   "XXXXXXXXXXXXXXXXX",
   "X.X.X.X.X.X.X.X.X",
   "XX.XX.XX.XX.XX.XX",
   "X.X.X.X.X.X.X.X.X",
   "XXXXXXXXXXXXXXXXX"
  ]
 },
 {
  "name": "wall_6",
  "w": 17,
  "h": 7,
  "cat": "wall",
  "kind": "sprite",
  "rows": [
   "XXXXXXXXXXXXXXXXX",
   "X................",
   "XXXXXXXXXXXXXXXXX",
   "X.X.X.X.X.X.X.X.X",
   "XX.XX.XX.XX.XX.XX",
   "X.X.X.X.X.X.X.X.X",
   "XXXXXXXXXXXXXXXXX"
  ]
 },
 {
  "name": "wall_7",
  "w": 23,
  "h": 7,
  "cat": "wall",
  "kind": "sprite",
  "rows": [
   "XXXXXXXXXXXXXXXXXXXXXXX",
   "X.....................X",
   "XXXXXXXXXXXXXXXXXXXXXXX",
   "X.X.X.X.X.X.X.X.X.X.X.X",
   "XX.XX.XX.XX.XX.XX.XX.XX",
   "X.X.X.X.X.X.X.X.X.X.X.X",
   "XXXXXXXXXXXXXXXXXXXXXXX"
  ]
 },
 {
  "name": "water",
  "w": 128,
  "h": 2,
  "cat": "ground",
  "kind": "sprite",
  "rows": [
   "...B...B...B...B...B...B...B...BB...B...B...B...B...B...B...B....B...B...B...B...B...B...B...B....B...B...B...B...B...B...B...B.",
   "BBB.BBB.BBB.BBB.BBB.BBB.BBB.BBB..BBB.BBB.BBB.BBB.BBB.BBB.BBB.BBBB.BBB.BBB.BBB.BBB.BBB.BBB.BBB.BBBB.BBB.BBB.BBB.BBB.BBB.BBB.BBB.B"
  ]
 },
 {
  "name": "well",
  "w": 9,
  "h": 12,
  "cat": "prop",
  "kind": "sprite",
  "rows": [
   "....X....",
   "...XXX...",
   "..XXXXX..",
   ".XXX.XXX.",
   "XXXXXXXXX",
   ".X.....X.",
   ".X..X..X.",
   ".X..X..X.",
   ".X.XXX.X.",
   "XXXXXXXXX",
   "X.XXXXX.X",
   "XXXX.XXXX"
  ]
 },
 {
  "name": "windmill_top",
  "w": 21,
  "h": 19,
  "cat": "roof",
  "kind": "sprite",
  "rows": [
   ".X.................X.",
   "X.X...............X.X",
   "...X.............X...",
   "....X.....X.....X....",
   "...X.X...XXX...X.X...",
   "......X.XXXXX.X......",
   ".......X.XXXXX.......",
   "......XXXXXXXXX......",
   ".....XXXXXXXX.XX.....",
   "........oXoXo........",
   ".....ooooXXXoooo.....",
   ".....oXoXoooXoXo.....",
   ".....ooXoo.ooXoo.....",
   "..ooooXoo...ooXoooo..",
   "..oXoXoo.....ooXoXo..",
   "..ooXoo.......ooXoo..",
   "oooXoo.........ooXooo",
   "XoXoo...........ooXoX",
   "oXoo.............ooXo"
  ],
  "meta": {
   "drop": 10
  }
 }
]
