// Generated by `npm run vendor:icons` from public/dither/icons/manifest.json
// (authored in the sibling dither-studio repo, commit b81a4ad).
// Do not edit by hand; re-run the script after `make export-icons` ships a
// new set.

export const ICON_NAMES = [
  "arrow-down",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "bell",
  "bookmark",
  "calendar",
  "camera",
  "cart",
  "chat",
  "check",
  "chevron-down",
  "chevron-right",
  "clock",
  "close",
  "copy",
  "download",
  "edit",
  "eye",
  "file",
  "filter",
  "folder",
  "globe",
  "grid",
  "heart",
  "home",
  "image",
  "info",
  "list",
  "lock",
  "mail",
  "menu",
  "minus",
  "moon",
  "pause",
  "pin",
  "play",
  "plus",
  "question",
  "refresh",
  "search",
  "settings",
  "share",
  "star",
  "stop",
  "sun",
  "trash",
  "upload",
  "user",
  "volume",
  "warning"
] as const

export const ICON_STYLES = [
  "filled",
  "outline"
] as const

export const ICON_SIZES = [
  12,
  16,
  20,
  24,
  32,
  48
] as const

export type IconName = (typeof ICON_NAMES)[number]
export type IconStyle = (typeof ICON_STYLES)[number]
export type IconSize = (typeof ICON_SIZES)[number]

export const ICONS_COMMIT = "b81a4ad"

export function iconUrl(name: IconName, style: IconStyle, size: IconSize): string {
  return `/dither/icons/${name}-${style}-${size}.png`
}
