/**
 * AUTO-GENERATED by scripts/vendor-icons.mjs — do not edit by hand.
 * Source of truth: public/dither/icons/manifest.json (dither-studio
 * export, generator commit 23c786f).
 */

export type DitherIconName = "arrow-down" | "arrow-left" | "arrow-right" | "arrow-up" | "bell" | "bookmark" | "calendar" | "camera" | "cart" | "chat" | "check" | "chevron-down" | "chevron-right" | "clock" | "close" | "copy" | "download" | "edit" | "eye" | "file" | "filter" | "folder" | "globe" | "grid" | "heart" | "home" | "image" | "info" | "list" | "lock" | "mail" | "menu" | "minus" | "moon" | "pause" | "pin" | "play" | "plus" | "question" | "refresh" | "search" | "settings" | "share" | "star" | "stop" | "sun" | "trash" | "upload" | "user" | "volume" | "warning"

export type DitherIconStyle = "filled" | "outline"

export type DitherIconSize = 12 | 16 | 20 | 24 | 32 | 48

export const DITHER_ICON_NAMES: DitherIconName[] = [
  "arrow-down",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "bell",
  "bookmark",
  "calendar",
  "camera",
  "cart",
  "chat",
  "check",
  "chevron-down",
  "chevron-right",
  "clock",
  "close",
  "copy",
  "download",
  "edit",
  "eye",
  "file",
  "filter",
  "folder",
  "globe",
  "grid",
  "heart",
  "home",
  "image",
  "info",
  "list",
  "lock",
  "mail",
  "menu",
  "minus",
  "moon",
  "pause",
  "pin",
  "play",
  "plus",
  "question",
  "refresh",
  "search",
  "settings",
  "share",
  "star",
  "stop",
  "sun",
  "trash",
  "upload",
  "user",
  "volume",
  "warning"
]

export const DITHER_ICON_SIZES: DitherIconSize[] = [12,16,20,24,32,48]

/** Retina partner (2x) for each native size, when the set carries one. */
export const DITHER_ICON_2X: Partial<Record<DitherIconSize, DitherIconSize>> = {
  12: 24,
  16: 32,
  24: 48,
}

export function ditherIconUrl(
  name: DitherIconName,
  style: DitherIconStyle,
  size: DitherIconSize,
): string {
  return `/dither/icons/${name}-${style}-${size}.png`
}
