// Region map for the Urizen OneBit v2 sheet (206 x 50 cells, 12px tiles, 1px gaps).
//
// Each region: { c: [col0, col1], r: [row0, row1], cat, names?, span?, tags? }
//   c / r   inclusive cell ranges
//   cat     "category/subcategory" (the id prefix)
//   names   space-separated names, assigned to the region's NON-EMPTY cells
//           (or span blocks) in reading order. Use "-" to keep the default.
//           Cells without a name become `<subcategory>_<nn>`.
//   span    [w, h] to treat w x h cell blocks as one asset (anchored at c0/r0)
//   tags    extra tags
//
// Later regions override earlier ones, so broad areas go first.
// Edit freely, then run `npm run tiles` (tiles you edited in /dev/tiles are kept).

export const regions = [
  // ---------------------------------------------------------------- sheet 0: fantasy world + items
  { c: [0, 24], r: [0, 0], cat: 'structure/wall' },
  { c: [23, 24], r: [0, 0], cat: 'structure/stairs', names: 'stairs_down stairs_up' },
  { c: [0, 20], r: [1, 1], cat: 'structure/door' },
  { c: [0, 19], r: [2, 2], cat: 'structure/stone_wall' },
  { c: [20, 21], r: [2, 3], cat: 'structure/door', tags: ['stone'] },
  { c: [22, 24], r: [2, 4], cat: 'structure/dark_wall' },
  { c: [0, 19], r: [3, 3], cat: 'structure/brick_wall' },
  { c: [0, 10], r: [4, 4], cat: 'structure/wood_wall' },
  { c: [11, 16], r: [4, 4], cat: 'structure/window' },
  { c: [0, 21], r: [5, 7], cat: 'terrain/floor' },
  { c: [0, 6], r: [8, 8], cat: 'nature/tree', names: 'oak oak_2 willow pine sapling palm palm_2' },
  { c: [23, 24], r: [8, 10], cat: 'nature/vine' },
  { c: [0, 21], r: [9, 9], cat: 'nature/plant', names: 'cactus sprout lily_pad grass grass_2 grass_3 reeds' },
  { c: [0, 5], r: [10, 10], cat: 'nature/plant', names: 'flowers_red coral_red mushroom_red mushroom_white stump dead_tree' },
  { c: [0, 24], r: [11, 11], cat: 'terrain/rock' },
  { c: [0, 24], r: [12, 12], cat: 'terrain/water' },
  { c: [0, 24], r: [13, 13], cat: 'terrain/dirt' },
  { c: [0, 16], r: [14, 14], cat: 'creatures/animal', names: 'cat cat_dark snake rat dog llama squirrel crab bat elephant whale rock_beast lion lizard bear fish' },
  { c: [24, 24], r: [14, 14], cat: 'effects/sparkle' },
  { c: [0, 24], r: [15, 15], cat: 'creatures/bug', names: 'beetle butterfly spider wasp hornet moth snail centipede beetle_tan beetle_tan_2 ant ant_2 jellyfish jellyfish_2 jellyfish_3 squid' },
  { c: [0, 24], r: [16, 16], cat: 'creatures/animal', names: 'horse pony pig rabbit hare goose duck duckling chicken chick deer' },
  { c: [0, 24], r: [17, 18], cat: 'food/produce', names: 'mushroom steak carrot apple bean_pod drumstick cherries cheese egg leaf pumpkin blueberries grapes acorn acorn_2 orange potato pear chili banana corn radish leek beet strawberry peas banana_single grapes_blue eggplant cucumber tomato herb herbs turnip cabbage raspberry sausage garlic potatoes shrimp onion ham sweet_potato meat fish_fillet' },
  { c: [0, 24], r: [19, 20], cat: 'food/meal' },
  { c: [0, 24], r: [21, 21], cat: 'food/kitchen', names: 'jug bowl bottle bottle_2 spoon fork cutlery pot bread_tin wine_bottle wine_glass cup teapot teapot_2 teapot_3 samovar cauldron stove' },
  { c: [0, 24], r: [22, 22], cat: 'items/gem', names: 'crystal diamond emerald orb crystal_cluster crystal_cluster_2 geode' },
  { c: [0, 24], r: [23, 23], cat: 'items/material', names: 'log ore gingerbread cloth wool feather copper_bar cracker' },
  { c: [0, 24], r: [24, 24], cat: 'nature/farm', names: 'wheat wheat_2 wheat_3 hay scarecrow sprouts sprouts_2 seedling cotton doghouse scarecrow_small' },
  { c: [0, 24], r: [25, 25], cat: 'effects/slash', names: 'slash claw lash blood blood_splat blood_splat_2' },
  { c: [0, 24], r: [26, 27], cat: 'armor/chest' },
  { c: [8, 12], r: [26, 26], cat: 'armor/dress' },
  { c: [0, 9], r: [28, 28], cat: 'armor/legs', names: 'pants shorts skirt_pink skirt_teal leggings - - - - leggings_dark' },
  { c: [12, 24], r: [28, 28], cat: 'armor/robe' },
  { c: [0, 24], r: [29, 29], cat: 'armor/accessory', names: 'belt boot boot_2 glove glove_2 boots boots_2 gauntlets gauntlets_2 bracelet bracelet_2 bracers tall_boot greaves' },
  { c: [0, 24], r: [30, 30], cat: 'armor/hat', names: 'helm helm_2 cowboy_hat hat bowler_hat hat_2 top_hat top_hat_2 feather_hat chef_hat' },
  { c: [0, 14], r: [31, 31], cat: 'items/tool', names: 'shovel pickaxe pliers fishing_rod rake_hand hammer scissors crowbar rake pitchfork broom saw watering_can sewing_machine knife' },
  { c: [15, 24], r: [31, 31], cat: 'items/instrument', names: 'harp lute flute guitar rope cane' },
  { c: [0, 24], r: [32, 32], cat: 'furniture/bed', tags: ['water'] },
  { c: [0, 22], r: [33, 33], cat: 'structure/house' },
  { c: [23, 24], r: [33, 33], cat: 'structure/tent' },
  { c: [0, 24], r: [34, 34], cat: 'terrain/overworld', names: 'forest forest_2 pines pines_2 swamp field wheat_field autumn snow waves dead_forest jungle grass hills hills_2 mountains volcano snow_peak desert dune' },
  { c: [0, 24], r: [35, 35], cat: 'furniture/table' },
  { c: [0, 24], r: [36, 36], cat: 'furniture/furniture', names: 'bed bed_double bookshelf bookshelf_2 dresser stool table crate chest_open drawer drawer_2 barrel barrel_2 wardrobe sofa chair chair_2 chair_3 chair_4 stall basket rug rug_2 rug_3' },
  { c: [0, 24], r: [37, 37], cat: 'items/paper', names: 'scroll scroll_2 note note_2 frame frame_2 book book_2' },
  { c: [0, 24], r: [38, 38], cat: 'items/bone', names: 'bones skull bone_pile ribs skeleton_pile bone horn tooth fang bone_2' },
  { c: [0, 3], r: [39, 39], cat: 'structure/cobweb' },
  { c: [4, 4], r: [39, 39], cat: 'structure/cobweb', names: 'web' },
  { c: [5, 24], r: [39, 39], cat: 'structure/grave', names: 'tombstone tombstone_2 tombstone_3 cross' },
  { c: [0, 24], r: [40, 40], cat: 'props/misc', names: 'ladder crate crate_2 cage cabinet cabinet_2 fence fence_2 fence_3 fence_4 hay_bale log_pile wagon ladder_2 spiderweb anvil_stand round_table rug_oval whip anchor fountain' },
  { c: [0, 24], r: [41, 41], cat: 'terrain/deep_water' },
  { c: [0, 24], r: [42, 42], cat: 'props/light', names: 'campfire fireplace oven candle torch lantern flame candle_red wand_red shrine firework brazier lava_lamp' },
  { c: [0, 10], r: [43, 44], cat: 'items/jewelry', names: 'amulet amulet_2 amulet_3 amulet_4 amulet_5 amulet_6 medal medal_2 medal_3 medal_4 medal_5 pendant pendant_2 pendant_3 pendant_4 pendant_5 pendant_6 medallion medallion_2 medallion_3 medallion_4 medallion_5' },
  { c: [11, 24], r: [43, 44], cat: 'items/jewelry', names: 'ring ring_2 ring_3 ring_4 ring_5 ring_6 ring_7' },
  { c: [0, 9], r: [45, 45], cat: 'items/key', names: 'key_copper key_copper_2 key_iron key_iron_2 key_gold key_gold_2 key_brass key_brass_2 key_ornate key_ornate_2' },
  { c: [10, 24], r: [45, 45], cat: 'items/lock', names: 'padlock padlock_2 padlock_3 padlock_4' },
  { c: [0, 24], r: [46, 46], cat: 'items/treasure', names: 'coins gold_coin gold_bar cookie silver_coin gold_medal copper_coins silver_stack gold_stack' },
  { c: [0, 24], r: [47, 47], cat: 'props/market', names: 'stall stall_2 stall_3 vase pot sack jar pail bell_gold birdhouse birdhouse_2 urn' },
  { c: [0, 24], r: [48, 48], cat: 'props/chain', names: 'chain chain_2 chain_3 pillar pillar_2 pillar_3 hook rope rope_pole' },
  { c: [0, 24], r: [49, 49], cat: 'magic/effect', names: 'portal portal_2 tornado frost' },

  // ---------------------------------------------------------------- sheet 1: dungeon, weapons, magic
  { c: [26, 50], r: [0, 0], cat: 'structure/fence' },
  { c: [26, 45], r: [1, 1], cat: 'structure/house', names: 'house house_2 hall hall_2 house_3 windmill windmill_2 hut sign_board' },
  { c: [26, 45], r: [2, 3], cat: 'structure/landmark', names: 'castle castle_2 fort fort_2 palace palace_2 palace_3 pyramid temple temple_2 bank mosque palace_4 pagoda ziggurat castle_3 column statue torii shrine cave torii_2' },
  { c: [46, 50], r: [1, 3], cat: 'structure/tower', span: [1, 3], names: 'bell_tower column lighthouse_brick lighthouse stone_tower' },
  { c: [26, 50], r: [4, 4], cat: 'items/potion', names: 'vial_purple vial_purple_2 flask_green flask_green_2 flask_red flask_red_2 flask_blue flask_blue_2 flask_yellow flask_yellow_2 jar_green potion_pink potion_cyan potion_brown potion_blue potion_teal potion_orange potion_dark_green potion_red potion_lime potion_gold potion_mauve' },
  { c: [26, 50], r: [5, 5], cat: 'structure/gate' },
  { c: [26, 40], r: [6, 6], cat: 'weapons/sword', names: 'broadsword longsword greatsword sword sword_2 golden_sword scimitar falchion katana cutlass short_sword dagger_long rapier claymore bastard_sword' },
  { c: [41, 42], r: [6, 6], cat: 'weapons/sword', names: 'flame_blade' },
  { c: [43, 50], r: [6, 6], cat: 'weapons/dagger', names: 'dagger dagger_2 twin_daggers' },
  { c: [26, 50], r: [7, 7], cat: 'weapons/blunt', names: 'mace morningstar club war_club club_2 flail' },
  { c: [26, 50], r: [8, 8], cat: 'weapons/polearm', names: 'halberd trident spear lance golden_spear pitchfork pike pike_2 javelin glaive partisan ranseur' },
  { c: [26, 50], r: [9, 9], cat: 'weapons/axe', names: 'battle_axe axe hatchet hatchet_2 pickaxe war_axe war_hammer maul double_axe scythe bardiche halberd_axe double_bit copper_axe' },
  { c: [26, 30], r: [10, 10], cat: 'weapons/bow', names: 'bow recurve longbow crossbow ballista' },
  { c: [31, 42], r: [10, 10], cat: 'weapons/arrow', names: 'arrow arrow_2 arrow_3' },
  { c: [43, 50], r: [10, 10], cat: 'weapons/thrown', names: 'boomerang sickle sword_thrown net_bolas kunai magnet shuriken net' },
  { c: [26, 37], r: [11, 11], cat: 'armor/shoulder', names: 'pauldrons pauldrons_2 pauldrons_3 spaulders spaulders_2 fur_mantle' },
  { c: [26, 37], r: [12, 12], cat: 'armor/shield', names: 'heater_shield tower_shield round_shield' },
  { c: [38, 50], r: [12, 12], cat: 'armor/helm', names: 'horned_helm dome_helm bucket_helm great_helm' },
  { c: [26, 37], r: [13, 13], cat: 'magic/spell', names: 'rune_circle summon vortex altar sparkles hex_mound' },
  { c: [38, 41], r: [13, 13], cat: 'magic/portal', names: 'arch arch_2' },
  { c: [42, 50], r: [13, 13], cat: 'weapons/staff', names: 'staff staff_2 staff_3 staff_4 staff_wood serpent_staff lightning_staff' },
  { c: [26, 50], r: [14, 14], cat: 'items/book', names: 'scroll scroll_2 scroll_3 scroll_4 scroll_5 spyglass ticket ticket_2 ticket_3 open_book open_book_2 spellbook spellbook_2 spellbook_3 spellbook_4' },
  { c: [26, 50], r: [15, 16], cat: 'ui/sign' },
  { c: [26, 50], r: [17, 17], cat: 'magic/rune' },
  { c: [26, 50], r: [19, 19], cat: 'items/chest', names: 'chest chest_open chest_2 chest_3 chest_4 chest_5 chest_6 chest_small' },
  { c: [26, 50], r: [20, 20], cat: 'props/sign', names: 'signpost signpost_2 signpost_3 notice_board sign_arrows gallows gallows_2 rope_coil rope_coil_2 cauldron cauldron_2 cauldron_3' },
  { c: [26, 30], r: [21, 21], cat: 'structure/portcullis' },
  { c: [31, 50], r: [21, 21], cat: 'structure/drape' },
  { c: [26, 50], r: [22, 22], cat: 'props/light', names: 'lantern_red brazier brazier_2 cart_fire candle_stub' },
  { c: [26, 47], r: [23, 23], cat: 'items/regalia', names: 'crown crown_2 skeleton_key flag flag_2 flag_3 flag_4 flag_5 flag_6 banner candelabra necklace throne' },
  { c: [48, 50], r: [23, 24], cat: 'ui/banner', span: [3, 2], names: 'scroll_banner' },
  { c: [47, 47], r: [24, 24], cat: 'ui/banner', names: 'scroll_end' },
  { c: [26, 31], r: [24, 24], cat: 'props/decor', names: 'pawn statue bishop throne globe telescope' },
  { c: [32, 33], r: [24, 24], cat: 'props/decor', span: [2, 1], names: 'ship' },
  { c: [26, 45], r: [25, 25], cat: 'props/misc', names: 'cauldron cauldron_2 anvil anvil_2 forge chest_iron cross star_statue star_statue_dark obelisk bell chalice bed_frame torch_stand horseshoe cane coffin goblet goblet_2' },
  { c: [46, 50], r: [25, 26], cat: 'items/map' },
  { c: [26, 32], r: [26, 26], cat: 'items/art', names: 'quill quill_2 feather_pen mirror easel palette brush' },
  { c: [26, 45], r: [27, 27], cat: 'nature/potted', names: 'gift clover santa_hat potted_plant potted_flower sprout sprout_2 potted_lavender potted_rose' },
  { c: [26, 45], r: [28, 28], cat: 'creatures/worm' },
  { c: [26, 45], r: [29, 29], cat: 'props/cart', names: 'minecart minecart_2 minecart_3 minecart_ore minecart_gold demon_cart minecart_crown cage_cart cage_cart_2' },
  { c: [26, 28], r: [42, 44], cat: 'magic/portal', span: [3, 3], names: 'stone_portal' },
  { c: [29, 36], r: [42, 44], cat: 'effects/particles', names: 'blood_rain blood_rain_2 blood_rain_3 blood_rain_4 bubbles bubbles_2 bubbles_3 bubbles_4 sparkle sparkle_2 sparkle_3 sparkle_4' },
  { c: [26, 37], r: [45, 45], cat: 'heraldry/shield', names: 'red orange yellow green blue purple crimson pink gold gold_2 gray rust' },
  { c: [26, 37], r: [46, 47], cat: 'heraldry/banner', span: [1, 2], names: 'red orange yellow green blue purple crimson pink gold gold_2 gray rust' },
  { c: [48, 50], r: [45, 47], cat: 'magic/circle', span: [3, 3], names: 'summoning_circle' },
  { c: [26, 45], r: [48, 49], cat: 'creatures/boss', span: [2, 2], names: 'archmage demon_skull hydra fire_elemental slime_king flesh_golem giant_spider moth_queen kraken anglerfish' },
  { c: [47, 47], r: [48, 49], cat: 'creatures/boss', names: 'hooded_small' },
  { c: [48, 50], r: [48, 49], cat: 'creatures/boss', span: [1, 2], names: 'hooded treant golem' },

  // ---------------------------------------------------------------- sheet 2: modern world
  { c: [52, 76], r: [0, 1], cat: 'modern/wall' },
  { c: [52, 76], r: [2, 2], cat: 'modern/structure' },
  { c: [69, 76], r: [2, 2], cat: 'modern/vehicle', names: 'car_blue car_red tram car_gray train train_front train_back' },
  { c: [52, 74], r: [3, 4], cat: 'modern/road' },
  { c: [75, 76], r: [3, 4], cat: 'modern/lamp', span: [1, 2], names: 'streetlamp streetlamp_2' },
  { c: [52, 76], r: [5, 5], cat: 'modern/road_sign' },
  { c: [52, 76], r: [6, 6], cat: 'modern/building' },
  { c: [52, 76], r: [7, 7], cat: 'modern/vehicle' },
  { c: [52, 76], r: [8, 8], cat: 'modern/facade' },
  { c: [52, 76], r: [9, 9], cat: 'modern/medical', names: 'battery_pack bolt battery battery_2 battery_3 cable medkit medkit_2 first_aid capsule pill watch pill_white syringe syringe_2 syringe_3 injector blood_bag bandage pill_bottle flask beaker stethoscope' },
  { c: [52, 58], r: [10, 11], cat: 'modern/keycard' },
  { c: [59, 76], r: [10, 11], cat: 'modern/badge' },
  { c: [52, 76], r: [12, 12], cat: 'modern/tech', names: 'circuit circuit_2 usb cassette cassette_2 cd guitar_pick floppy' },
  { c: [52, 76], r: [13, 13], cat: 'modern/appliance' },
  { c: [52, 76], r: [14, 14], cat: 'modern/can' },
  { c: [52, 69], r: [15, 15], cat: 'modern/gun', names: 'pistol revolver revolver_2 revolver_3 blaster flintlock smg rifle assault_rifle assault_rifle_2 shotgun sniper rocket_launcher musket rifle_2 rifle_3' },
  { c: [68, 76], r: [15, 15], cat: 'modern/gear' },
  { c: [52, 76], r: [16, 18], cat: 'modern/item' },
  { c: [52, 76], r: [19, 19], cat: 'modern/electronics' },
  { c: [52, 76], r: [20, 20], cat: 'modern/office' },
  { c: [52, 76], r: [21, 23], cat: 'modern/screen' },
  { c: [52, 54], r: [21, 23], cat: 'modern/computer', span: [3, 3], names: 'crt_computer' },
  { c: [52, 66], r: [24, 29], cat: 'modern/pipe' },
  { c: [76, 76], r: [27, 29], cat: 'modern/lamp', span: [1, 3], names: 'lamp_post' },
  { c: [52, 62], r: [30, 32], cat: 'modern/money' },
  { c: [63, 76], r: [30, 30], cat: 'modern/money', names: 'money_bag coin_dollar' },
  { c: [52, 76], r: [35, 35], cat: 'modern/panel' },
  { c: [52, 76], r: [36, 36], cat: 'modern/lever' },
  { c: [52, 76], r: [37, 37], cat: 'modern/button' },
  { c: [52, 76], r: [38, 40], cat: 'modern/machine' },
  { c: [52, 76], r: [41, 41], cat: 'modern/gauge', names: 'gauge_blue gauge_green gauge_yellow gauge_orange gauge_red' },

  // ---------------------------------------------------------------- sheet 3: sci-fi, space, UI, font
  { c: [78, 102], r: [0, 2], cat: 'scifi/wall' },
  { c: [78, 102], r: [4, 5], cat: 'scifi/ship' },
  { c: [78, 102], r: [6, 6], cat: 'scifi/weapon', names: 'laser_pistol laser_pistol_2 blaster blaster_2 blaster_3 blaster_4 blaster_5 blaster_6 blaster_7 railgun energy_cell lightsaber robot_head' },
  { c: [78, 102], r: [7, 7], cat: 'scifi/tech', names: 'server energy_tank chip chip_2' },
  { c: [78, 102], r: [11, 12], cat: 'scifi/alien' },
  { c: [78, 102], r: [13, 15], cat: 'scifi/astronaut' },
  { c: [78, 81], r: [16, 17], cat: 'space/body', span: [2, 2], names: 'sun planet_large' },
  { c: [78, 102], r: [18, 18], cat: 'space/deep', names: 'galaxy nebula ring comet comet_2 spiral' },
  { c: [78, 102], r: [19, 19], cat: 'space/planet' },
  { c: [78, 102], r: [20, 20], cat: 'space/asteroid' },
  { c: [78, 102], r: [21, 21], cat: 'space/star' },
  { c: [78, 92], r: [23, 25], cat: 'scifi/terminal' },
  { c: [93, 102], r: [24, 25], cat: 'effects/laser' },
  { c: [78, 102], r: [28, 28], cat: 'cards/hearts', names: 'ace_low 2 3 4 5 6 7 8 9 10 jack queen king ace' },
  { c: [78, 102], r: [29, 29], cat: 'cards/diamonds', names: 'ace_low 2 3 4 5 6 7 8 9 10 jack queen king ace' },
  { c: [78, 102], r: [30, 30], cat: 'cards/spades', names: 'ace_low 2 3 4 5 6 7 8 9 10 jack queen king ace' },
  { c: [78, 102], r: [31, 31], cat: 'cards/clubs', names: 'ace_low 2 3 4 5 6 7 8 9 10 jack queen king ace' },
  { c: [78, 102], r: [33, 36], cat: 'ui/icon' },
  { c: [78, 102], r: [37, 37], cat: 'ui/stat', names: 'heart heart_2 heart_broken heart_half heart_piece mana mana_half water_magic poison ice_shard frost water ice' },
  { c: [78, 102], r: [38, 38], cat: 'ui/icon_2', names: 'cross_box check_box empty_box daggers crossed_swords eye sad happy tentacles beast rot lips poison_bag hourglass' },
  { c: [78, 102], r: [39, 39], cat: 'ui/stat_2', names: 'arrow_down arrow_up lightning sparkles sun drop blood moon_full moon_waning moon_half moon_crescent moon_new moon_crescent_2 moon_half_2 moon_waxing' },
  { c: [78, 102], r: [40, 40], cat: 'ui/tiny' },
  { c: [78, 102], r: [44, 44], cat: 'font/regular', names: 'A B C D E F G H I J K L M N O P Q R S T 1 2 3 4 5' },
  { c: [78, 102], r: [45, 45], cat: 'font/regular', names: 'U V W X Y Z a b c d e f g h i j k l m n 6 7 8 9 0' },
  { c: [78, 102], r: [46, 46], cat: 'font/regular', names: 'o p q r s t u v w x y z paren_l paren_r bracket_l bracket_r brace_l brace_r lt gt plus minus question exclaim caret' },
  { c: [78, 102], r: [47, 47], cat: 'font/regular', names: 'colon hash underscore at percent tilde dollar quote apostrophe amp star equals backtick pipe slash backslash period comma semicolon' },
  { c: [97, 102], r: [47, 47], cat: 'font/bold', names: 'A B C D E F' },
  { c: [78, 102], r: [48, 48], cat: 'font/bold', names: 'G H I J K L M N O P Q R S T U V W X Y Z a b c d e' },
  { c: [78, 102], r: [49, 49], cat: 'font/bold', names: 'f g h i j k l m n o p q r s t u v w x y z question_rainbow' },

  // ---------------------------------------------------------------- sheet 4: characters
  // Rows 0-35 are a roster (see ROSTER below): generated as characters/<race>_<class>.
  { c: [104, 120], r: [36, 37], cat: 'creatures/humanoid' },
  { c: [104, 205], r: [38, 38], cat: 'characters/group' },
  { c: [104, 106], r: [39, 39], cat: 'characters/misc' },
  { c: [107, 110], r: [39, 39], cat: 'creatures/animal', names: 'camel_rider camel camel_2 camel_3' },
  { c: [104, 205], r: [40, 41], cat: 'creatures/monster' },
  { c: [104, 205], r: [42, 42], cat: 'creatures/monster', names: 'slime slime_big cube_face mandrake blob eyeball ghost treant dragon unicorn myconid centaur worm_coil' },
  { c: [104, 205], r: [43, 44], cat: 'characters/modern' },
  { c: [104, 205], r: [46, 47], cat: 'characters/pose' },
]

// Character roster: rows 0-35, cols 104-205. Row = race/variant, column = class/loadout.
// Rename these and re-run `npm run tiles` to rename every tile in the row/column at once.
export const ROSTER = {
  c: [104, 205],
  r: [0, 35],
  races: [
    'base', 'base_armored', 'gray', 'gray_2', 'green', 'orange', 'red', 'teal', 'green_dark', 'moss',
    'bone', 'blue', 'blue_2', 'shadow', 'cyan', 'umber', 'rust', 'purple', 'azure', 'crimson',
    'imp', 'cobalt', 'amber', 'slate', 'ochre', 'devil', 'pale', 'green_hat', 'witch', 'angel',
    'lilac_angel', 'goblin', 'treefolk', 'naga_sand', 'naga_blue', 'naga_blue_2',
  ],
  // Leave empty to use class_<nn> (nn = column offset from 104).
  classes: [],
}
