/**
 * DitherIcon — the dither-studio 1-bit icon set, tinted via CSS mask.
 *
 * The shipped PNGs are a black glyph on a transparent ground, so using
 * them as an alpha mask over a currentColor background makes every icon
 * inherit its text color for free (menu rows, hovers, the accent, egg
 * themes). Sizes are native renders, never scaled: `size` must be one of
 * the set's pixel grids, and where the set carries a 2x partner
 * (12↔24, 16↔32, 24↔48) it rides along via image-set for retina.
 *
 * Vocabulary/types come from src/lib/dither/icons.ts, regenerated by
 * `npm run vendor:icons` after a dither-studio `make export-icons`.
 */

import {
  DITHER_ICON_2X,
  ditherIconUrl,
  type DitherIconName,
  type DitherIconSize,
  type DitherIconStyle,
} from '../lib/dither/icons'

export default function DitherIcon({
  name,
  style = 'outline',
  size = 16,
  className,
  title,
}: {
  name: DitherIconName
  style?: DitherIconStyle
  size?: DitherIconSize
  className?: string
  /** Accessible label; omitted = decorative (aria-hidden). */
  title?: string
}) {
  const url1x = ditherIconUrl(name, style, size)
  const twoX = DITHER_ICON_2X[size]
  const mask = twoX
    ? `image-set(url("${url1x}") 1x, url("${ditherIconUrl(name, style, twoX)}") 2x)`
    : `url("${url1x}")`

  return (
    <span
      className={`dicon${className ? ` ${className}` : ''}`}
      role={title ? 'img' : undefined}
      aria-label={title}
      aria-hidden={title ? undefined : true}
      style={{
        width: size,
        height: size,
        WebkitMaskImage: mask,
        maskImage: mask,
      }}
    />
  )
}
