// Avatar roster baker: picks the Urizen character tiles the avatar can use.
//
//   node scripts/bake-avatars.mjs
//
// Reads   src/data/tileIndex.ts (tile positions) + public/tiles/urizen.png
// Writes  src/game/avatarTiles.ts
//
// The avatar renders tiles as one-color silhouettes, so only races whose
// silhouettes differ (hoods, hats, horns, tails) are kept; color-only
// variants would look identical. Tiles are dropped when their ink coverage
// says they aren't a standing figure: near-empty cells, or cells with an
// opaque background that would tint into a solid block. Roster column 97
// is a lying-down pose, and a few rows run past it into other art, so
// class_97 and up are always skipped.
// Deterministic and safe to re-run.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { decodePng } from './lib/png.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const INDEX = path.join(root, 'src/data/tileIndex.ts')
const SHEET = path.join(root, 'public/tiles/urizen.png')
const OUT = path.join(root, 'src/game/avatarTiles.ts')

const RACES = [
  'base', 'gray', 'purple', 'green_hat', 'witch', 'devil',
  'goblin', 'angel', 'treefolk', 'naga_blue',
]
const TILE = 12
const PITCH = 13
// share of the 144 cells that must be inked
const MIN_INK = 0.12
const MAX_INK = 0.55

const img = decodePng(fs.readFileSync(SHEET))
const ink = (col, row) => {
  let n = 0
  for (let y = 0; y < TILE; y++) {
    for (let x = 0; x < TILE; x++) {
      const px = 1 + col * PITCH + x
      const py = 1 + row * PITCH + y
      if (img.data[(py * img.width + px) * 4 + 3] > 0) n++
    }
  }
  return n / (TILE * TILE)
}

const src = fs.readFileSync(INDEX, 'utf8')
const entry = /"characters\/([a-z_0-9]+)\/(class_\d+)": \[(\d+), (\d+), 1, 1\]/g
const byRace = new Map(RACES.map((r) => [r, []]))
for (const m of src.matchAll(entry)) {
  const [, race, cls, x, y] = m
  if (!byRace.has(race) || Number(cls.slice(6)) >= 97) continue
  const cov = ink(+x, +y)
  if (cov < MIN_INK || cov > MAX_INK) continue
  byRace.get(race).push([+x, +y])
}

let total = 0
const lines = RACES.map((r) => {
  const cells = byRace.get(r)
  total += cells.length
  return `  // ${r} (${cells.length})\n  ${cells.map(([x, y]) => `[${x}, ${y}]`).join(', ')},`
})

fs.writeFileSync(
  OUT,
  `// GENERATED by scripts/bake-avatars.mjs. Do not edit; re-run the script.

/** Avatar figures as [col, row] cells on the Urizen sheet (${total} total). */
export const AVATAR_TILES: ReadonlyArray<readonly [number, number]> = [
${lines.join('\n')}
]
`
)
console.log(`wrote ${path.relative(root, OUT)}: ${total} figures`)
for (const r of RACES) console.log(`  ${r.padEnd(10)} ${byRace.get(r).length}`)
