// Tarot map baker: card id -> baked sheet cell.
//
//   node scripts/bake-tarot.mjs   (run after `npm run tiles`)
//
// Reads   src/data/tileIndex.ts (positions of the baked tarot/* tiles)
// Writes  src/game/tarotTiles.ts
//
// The card view renders faces via <TileBox> without pulling the 5k-entry
// tile index into the bundle (the gearTiles pattern). Fails loudly if the
// baked rows and the deck in src/data/tarot.ts drift apart.
// Deterministic and safe to re-run.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const INDEX = path.join(root, 'src/data/tileIndex.ts')
const OUT = path.join(root, 'src/game/tarotTiles.ts')

const index = fs.readFileSync(INDEX, 'utf8')
const cells = new Map()
for (const m of index.matchAll(/"tarot\/([a-z_0-9/]+)":\s*\[(\d+),\s*(\d+),\s*\d+,\s*\d+\]/g)) {
  cells.set(m[1], [Number(m[2]), Number(m[3])])
}

const SUITS = ['wands', 'cups', 'swords', 'pentacles']
const MAJORS = [
  'the_fool', 'the_magician', 'the_high_priestess', 'the_empress', 'the_emperor',
  'the_hierophant', 'the_lovers', 'the_chariot', 'strength', 'the_hermit',
  'wheel_of_fortune', 'justice', 'the_hanged_man', 'death', 'temperance',
  'the_devil', 'the_tower', 'the_star', 'the_moon', 'the_sun', 'judgement', 'the_world',
]
const RANKS = ['ace', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'page', 'knight', 'queen', 'king']

const expected = [
  ...MAJORS.map((s) => `major/${s}`),
  ...SUITS.flatMap((suit) => RANKS.map((r) => `${suit}/${r}`)),
  'back/back',
]
const missing = expected.filter((id) => !cells.has(id))
if (missing.length) {
  console.error(`tarot tiles missing from the sheet (run npm run tiles): ${missing.join(', ')}`)
  process.exit(1)
}

const lines = expected
  .filter((id) => id !== 'back/back')
  .map((id) => {
    // map key drops the tarot/ prefix and matches TarotCard.id exactly
    const [x, y] = cells.get(id)
    return `  '${id}': [${x}, ${y}],`
  })
const back = cells.get('back/back')

const out = `// GENERATED by scripts/bake-tarot.mjs. Do not edit; re-run the script.

/** Card id -> [col, row] of its 2x3 baked face on the Urizen sheet. */
export const TAROT_TILES: Readonly<Record<string, readonly [number, number]>> = {
${lines.join('\n')}
}

/** The card back (also the deck sprite). */
export const TAROT_BACK: readonly [number, number] = [${back[0]}, ${back[1]}]

/** All faces span 2x3 sheet cells. */
export const TAROT_TILE_W = 2
export const TAROT_TILE_H = 3
`
fs.writeFileSync(OUT, out)
console.log(`wrote ${OUT}: ${lines.length} faces + back at [${back}]`)
