// Gear art baker: resolves the character screen's item art to sheet cells.
//
//   node scripts/bake-gear.mjs
//
// Reads   src/data/tileIndex.ts (tile id -> position)
// Writes  src/game/gearTiles.ts
//
// GEAR below is the source of truth for what loot looks like: one entry per
// slot, listing its base types in order. The names must stay in step with
// BASES in src/game/loot.ts (the script checks and fails loudly if they
// drift), because a base index is what the save persists.
// Deterministic and safe to re-run.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const INDEX = path.join(root, 'src/data/tileIndex.ts')
const LOOT = path.join(root, 'src/game/loot.ts')
const OUT = path.join(root, 'src/game/gearTiles.ts')

/** slot -> [display name, tile id][] , in base-index order. */
const GEAR = {
  helm: [
    ['Dome Helm', 'armor/helm/dome_helm'],
    ['Horned Helm', 'armor/helm/horned_helm'],
    ['Bucket Helm', 'armor/helm/bucket_helm'],
    ['Great Helm', 'armor/helm/great_helm'],
    ['Feathered Hat', 'armor/hat/feather_hat'],
    ['Crown', 'items/regalia/crown'],
  ],
  weapon: [
    ['Short Sword', 'weapons/sword/short_sword'],
    ['Broadsword', 'weapons/sword/broadsword'],
    ['Katana', 'weapons/sword/katana'],
    ['Dagger', 'weapons/dagger/dagger'],
    ['Battle Axe', 'weapons/axe/battle_axe'],
    ['Mace', 'weapons/blunt/mace'],
    ['Staff', 'weapons/staff/staff'],
    ['Spear', 'weapons/polearm/spear'],
    ['Bow', 'weapons/bow/bow'],
  ],
  armor: [
    ['Tunic', 'armor/chest/chest_01'],
    ['Scale Mail', 'armor/chest/chest_05'],
    ['Chainmail', 'armor/chest/chest_11'],
    ['Plate', 'armor/chest/chest_12'],
    ['Robe', 'armor/robe/robe_02'],
    ['Mantle', 'armor/robe/robe_09'],
  ],
  shield: [
    ['Heater Shield', 'armor/shield/heater_shield'],
    ['Round Shield', 'armor/shield/round_shield'],
    ['Tower Shield', 'armor/shield/tower_shield'],
  ],
  ring: [
    ['Band', 'items/jewelry/ring'],
    ['Signet', 'items/jewelry/ring_2'],
    ['Seal Ring', 'items/jewelry/ring_3'],
    ['Gemmed Ring', 'items/jewelry/ring_5'],
    ['Loop', 'items/jewelry/ring_7'],
  ],
  boots: [
    ['Boots', 'armor/accessory/boots'],
    ['Sturdy Boots', 'armor/accessory/boots_2'],
    ['Tall Boots', 'armor/accessory/tall_boot'],
    ['Greaves', 'armor/accessory/greaves'],
  ],
  amulet: [
    ['Amulet', 'items/jewelry/amulet'],
    ['Talisman', 'items/jewelry/amulet_3'],
    ['Pendant', 'items/jewelry/pendant'],
    ['Charm', 'items/jewelry/pendant_3'],
    ['Medallion', 'items/jewelry/medallion'],
    ['Necklace', 'items/regalia/necklace'],
  ],
}

/** The loot chest visitors open on the character screen. */
const CHEST = 'items/chest/chest'

const index = fs.readFileSync(INDEX, 'utf8')
const cellFor = (id) => {
  const m = index.match(new RegExp(`"${id}": \\[(\\d+), (\\d+), 1, 1\\]`))
  if (!m) throw new Error(`tile id not found (or not 1x1): ${id}`)
  return [Number(m[1]), Number(m[2])]
}

// The save persists a base index, so BASES and GEAR must not drift apart.
const loot = fs.readFileSync(LOOT, 'utf8')
for (const [slot, entries] of Object.entries(GEAR)) {
  const m = loot.match(new RegExp(`^  ${slot}: \\[(.*)\\],$`, 'm'))
  if (!m) throw new Error(`BASES is missing the ${slot} slot`)
  const names = m[1].split(',').map((s) => s.trim().replace(/^'|'$/g, ''))
  const mine = entries.map(([name]) => name)
  if (names.join('|') !== mine.join('|')) {
    throw new Error(`BASES.${slot} does not match GEAR.${slot}:\n  loot.ts: ${names.join(', ')}\n  gear:    ${mine.join(', ')}`)
  }
}

const body = Object.entries(GEAR)
  .map(([slot, entries]) => {
    const cells = entries.map(([name, id]) => `[${cellFor(id).join(', ')}] /* ${name} */`)
    return `  ${slot}: [${cells.join(', ')}],`
  })
  .join('\n')

fs.writeFileSync(
  OUT,
  `// GENERATED by scripts/bake-gear.mjs. Do not edit; edit GEAR there and re-run.
import type { Slot } from './loot'

/** Sheet cell [col, row] for each slot's base types, in base-index order. */
export const GEAR_TILES: Record<Slot, ReadonlyArray<readonly [number, number]>> = {
${body}
}

/** The loot chest icon. */
export const CHEST_TILE: readonly [number, number] = [${cellFor(CHEST).join(', ')}]
`
)
const n = Object.values(GEAR).reduce((a, e) => a + e.length, 0)
console.log(`wrote ${path.relative(root, OUT)}: ${n} pieces of gear`)
