#!/usr/bin/env node
// Regenerates src/lib/dither/icons.ts from public/dither/icons/manifest.json,
// which the sibling dither-studio repo ships via `make export-icons`. Keeps
// icon names, styles and sizes compile-time checked without coupling the
// repos: the manifest and PNGs are vendored copies, same as vendor:ds.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const manifest = JSON.parse(
  readFileSync(resolve(root, 'public/dither/icons/manifest.json'), 'utf8'),
)

const list = (a) => JSON.stringify(a, null, 2)

const out = `// Generated by \`npm run vendor:icons\` from public/dither/icons/manifest.json
// (authored in the sibling dither-studio repo, commit ${manifest.commit}).
// Do not edit by hand; re-run the script after \`make export-icons\` ships a
// new set.

export const ICON_NAMES = ${list(manifest.icons)} as const

export const ICON_STYLES = ${list(manifest.styles)} as const

export const ICON_SIZES = ${list(manifest.sizes)} as const

export type IconName = (typeof ICON_NAMES)[number]
export type IconStyle = (typeof ICON_STYLES)[number]
export type IconSize = (typeof ICON_SIZES)[number]

export const ICONS_COMMIT = ${JSON.stringify(manifest.commit)}

export function iconUrl(name: IconName, style: IconStyle, size: IconSize): string {
  return \`/dither/icons/\${name}-\${style}-\${size}.png\`
}
`

writeFileSync(resolve(root, 'src/lib/dither/icons.ts'), out)
console.log(
  `vendored ${manifest.icons.length} icons x ${manifest.styles.length} styles x ` +
    `${manifest.sizes.length} sizes (dither-studio ${manifest.commit}) -> src/lib/dither/icons.ts`,
)
