// Regenerate src/lib/dither/icons.ts from the vendored icon manifest.
//
// The icon set is authored in the sibling dither-studio repo and shipped
// into public/dither/icons/ by its `make export-icons` (alpha ground,
// black glyph, one PNG per name/style/size). This script reads the
// manifest those exports write and bakes the vocabulary into a typed
// module, so DitherIcon can enforce valid names and native sizes at
// compile time. Full update loop:
//
//   make icons export-icons   # in dither-studio
//   npm run vendor:icons      # here, then commit both repos
//
// Deterministic: output depends only on manifest.json.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const manifestPath = join(root, 'public/dither/icons/manifest.json')
const outPath = join(root, 'src/lib/dither/icons.ts')

const m = JSON.parse(readFileSync(manifestPath, 'utf8'))
if (!Array.isArray(m.icons) || !Array.isArray(m.styles) || !Array.isArray(m.sizes)) {
  throw new Error('manifest.json missing icons/styles/sizes')
}

const lit = (arr) => arr.map((v) => JSON.stringify(v)).join(' | ')

const out = `/**
 * AUTO-GENERATED by scripts/vendor-icons.mjs — do not edit by hand.
 * Source of truth: public/dither/icons/manifest.json (dither-studio
 * export, generator commit ${m.commit}).
 */

export type DitherIconName = ${lit(m.icons)}

export type DitherIconStyle = ${lit(m.styles)}

export type DitherIconSize = ${m.sizes.join(' | ')}

export const DITHER_ICON_NAMES: DitherIconName[] = ${JSON.stringify(m.icons, null, 2)}

export const DITHER_ICON_SIZES: DitherIconSize[] = ${JSON.stringify(m.sizes)}

/** Retina partner (2x) for each native size, when the set carries one. */
export const DITHER_ICON_2X: Partial<Record<DitherIconSize, DitherIconSize>> = {
  12: 24,
  16: 32,
  24: 48,
}

export function ditherIconUrl(
  name: DitherIconName,
  style: DitherIconStyle,
  size: DitherIconSize,
): string {
  return \`/dither/icons/\${name}-\${style}-\${size}.png\`
}
`

writeFileSync(outPath, out)
console.log(`wrote ${outPath} (${m.icons.length} icons, commit ${m.commit})`)
