/**
 * TileAtlas — the public sprite browser behind /lab/tile-atlas.
 *
 * Fetches public/tiles/atlas.json (generated by `npm run tiles`) instead of
 * importing the manifest, so none of the 5k-entry data lands in the bundle.
 * Read-only: naming and categorizing happen in the dev-only /dev/tiles browser.
 */

import { useEffect, useMemo, useState } from 'react'
import { TileBox } from '../TileSprite'
import './TileAtlas.css'

type Row = [string, number, number, number?, number?]
interface Atlas {
  meta: { tile: number }
  cats: Record<string, Record<string, Row[]>>
}
interface Sprite {
  id: string
  name: string
  cat: string
  sub: string
  x: number
  y: number
  w: number
  h: number
  hay: string
}

const PAGE = 400

export default function TileAtlas() {
  const [atlas, setAtlas] = useState<Atlas | null>(null)
  const [failed, setFailed] = useState(false)
  const [q, setQ] = useState('')
  const [cat, setCat] = useState('')
  const [sub, setSub] = useState('')
  const [scale, setScale] = useState(3)
  const [shown, setShown] = useState(PAGE)
  const [sel, setSel] = useState<Sprite | null>(null)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    let live = true
    fetch('/tiles/atlas.json')
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(String(r.status)))))
      .then((d: Atlas) => live && setAtlas(d))
      .catch(() => live && setFailed(true))
    return () => {
      live = false
    }
  }, [])

  const sprites = useMemo<Sprite[]>(() => {
    if (!atlas) return []
    const out: Sprite[] = []
    for (const [c, subs] of Object.entries(atlas.cats))
      for (const [s, rows] of Object.entries(subs))
        for (const [name, x, y, w, h] of rows)
          out.push({ id: `${c}/${s}/${name}`, name, cat: c, sub: s, x, y, w: w ?? 1, h: h ?? 1, hay: `${c} ${s} ${name}`.toLowerCase() })
    return out
  }, [atlas])

  const counts = useMemo(() => {
    const m = new Map<string, number>()
    for (const s of sprites) m.set(s.cat, (m.get(s.cat) ?? 0) + 1)
    return [...m].sort((a, b) => a[0].localeCompare(b[0]))
  }, [sprites])

  const subs = useMemo(() => {
    if (!cat || !atlas) return []
    return Object.entries(atlas.cats[cat] ?? {})
      .map(([s, rows]) => [s, rows.length] as const)
      .sort((a, b) => a[0].localeCompare(b[0]))
  }, [cat, atlas])

  const matches = useMemo(() => {
    const terms = q.toLowerCase().split(/\s+/).filter(Boolean)
    return sprites.filter((s) => {
      if (cat && s.cat !== cat) return false
      if (sub && s.sub !== sub) return false
      return terms.every((t) => s.hay.includes(t))
    })
  }, [sprites, q, cat, sub])

  function choose(next: { cat?: string; sub?: string; q?: string }) {
    if (next.cat !== undefined) {
      setCat(next.cat)
      setSub('')
    }
    if (next.sub !== undefined) setSub(next.sub)
    if (next.q !== undefined) setQ(next.q)
    setShown(PAGE)
  }

  function copyId(id: string) {
    navigator.clipboard?.writeText(id).then(
      () => {
        setCopied(true)
        window.setTimeout(() => setCopied(false), 1400)
      },
      () => setCopied(false),
    )
  }

  if (failed)
    return <p className="atlas-note">The sprite data did not load. Run <code>npm run tiles</code> to regenerate it.</p>
  if (!atlas) return <p className="atlas-note">Loading sprites...</p>

  return (
    <div className="atlas">
      <div className="atlas-bar">
        <input
          id="atlas-search"
          type="search"
          value={q}
          onChange={(e) => choose({ q: e.target.value })}
          placeholder="search sword, potion, wall"
          aria-label="Search sprites"
        />
        <label className="atlas-zoom">
          zoom
          <input
            id="atlas-zoom"
            type="range"
            min={2}
            max={6}
            step={1}
            value={scale}
            onChange={(e) => setScale(Number(e.target.value))}
            aria-label="Zoom"
          />
        </label>
      </div>

      <div className="atlas-chips">
        <button type="button" aria-pressed={!cat} onClick={() => choose({ cat: '' })}>
          all <em>{sprites.length.toLocaleString()}</em>
        </button>
        {counts.map(([c, n]) => (
          <button key={c} type="button" aria-pressed={cat === c} onClick={() => choose({ cat: cat === c ? '' : c })}>
            {c} <em>{n.toLocaleString()}</em>
          </button>
        ))}
      </div>

      {subs.length > 1 && (
        <div className="atlas-chips atlas-subs">
          {subs.map(([s, n]) => (
            <button key={s} type="button" aria-pressed={sub === s} onClick={() => choose({ sub: sub === s ? '' : s })}>
              {s} <em>{n}</em>
            </button>
          ))}
        </div>
      )}

      <p className="atlas-count">
        {matches.length.toLocaleString()} {matches.length === 1 ? 'sprite' : 'sprites'}
        {sel && (
          <>
            {' · '}
            <button type="button" className="atlas-copy" onClick={() => copyId(sel.id)}>
              {copied ? 'copied' : sel.id}
            </button>
          </>
        )}
      </p>

      <div className="atlas-grid">
        {matches.slice(0, shown).map((s) => (
          <button
            key={s.id}
            type="button"
            className="atlas-cell"
            title={s.id}
            aria-label={s.id}
            aria-pressed={sel?.id === s.id}
            onClick={() => setSel(sel?.id === s.id ? null : s)}
          >
            <TileBox x={s.x} y={s.y} w={s.w} h={s.h} scale={scale} />
          </button>
        ))}
      </div>

      {matches.length === 0 && <p className="atlas-note">Nothing matches. The names are drafts, so try a plainer word.</p>}
      {matches.length > shown && (
        <button type="button" className="atlas-more" onClick={() => setShown(shown + PAGE)}>
          show {Math.min(PAGE, matches.length - shown)} more
        </button>
      )}
    </div>
  )
}
