// AUTO-GENERATED by scripts/lock-projects.mjs — do not edit by hand.
// Re-generate: LOCK_PASSWORD=... node scripts/lock-projects.mjs
// (plaintext sources live in content/locked/, gitignored; see its README)
//
// Each payload is the project's ProjectBlock[] as AES-GCM-256 ciphertext,
// keyed by a PBKDF2 derivation of the shared unlock password. Decryption
// happens in the browser via src/lib/vault.ts.

export const VAULT_KDF = {
  salt: 'sh-vault-v1',
  iterations: 310000,
  hash: 'SHA-256',
} as const

export interface LockedPayload {
  iv: string // base64, 12 bytes
  ct: string // base64 ciphertext + GCM tag
}

export const lockedBlocks: Record<string, LockedPayload> = {
  'sealed-demo': {
    iv: 'CkQy8ukyFn3+jEZj',
    ct: 'd4pcBWgUdexoDN+Vi7XlHFUxw55sLH+jrLdJzyzRGO20zk2v6kyKA2DtFbNcortiQvnpj92sUiTUx/cTlR7FBpQMS+Bo1wlXLAiG7D1WaUurzu00HUkTMHEQCLArrgLOii3CrXitizBMmCG4MC8A/wz8XyupkTP3gOg/9ba6/OXXLpO0oR4gm2KofEeO18MK1v53dmL4w7jMOdqE2MY9Ftd0whCg6sF0Fre6g/L5dcw8MtcblomP+MyW8bZS4o743NHqQdwJmVfgN5zkufROherbipkDuMqw3iwtHv5eq7SRxxO49cnBptJGErnW1m6wcIjhnovOcwvLCdar+qP2bN2WKRvGg3ZIa7KUjpcfprxvfmt+Rl8GCm9yH8UodGBcUTa1jj1AQy0bkfmuKqFGkzS7qzqjannta47VHkj2LHt/wXCMbGTHjgDnZhZ3k1BMjM64kUngxEjfxtmp79hJa5FK7DQXa67/pyHMVxVw3Zh8PvCQg5oZMvOmrDcjMYgkSIqFgjKUSsh+90zZoSJ4rI4eMbFR+71FSgKnjmDYomfdS8qIs5GNRzpQLwpISaVjR1lC7zijwzdvLk6YE/G3QHJ1Gq1DKbyeKdqS9fKZT2wDErJ8HChxOjXwnsgcn9H3QsHfeNqk9NGpOxs/SrHG0ROlaH7eL7HkYWBOxJtck+PUBqt28HZodhQdgtnsJRr9MVOX2OHyzagjwEYh/bVfzPT8YZJNS140RaA4Bx43Usbr1W9QDLJnmE00JdWh55uYqXOLrPBocTitD8CiOKOkIU5lD8qmAbWlh5Ngey7UIIf6UtlXSxrwJ2AiBTQHurpLqzdOgI9y4X1V/dnMWICau/BEU0peXjsYfjFODiM2rm6bQPMDk63gOVV6QLbEnrSmmzigRgm/yi3kRA9a+j9CXFpzGjONP1qYRpvjrqf1NByb5ySRQW4z+dgGOKykzXRoIeM1smCz9R3idNGithgK1ernt/ZeH2kJXLYkHzUweBQop2jIg0JvVupSZVLUaZc91zyBWL3t4gW+YLoNfu/C3cM2XCO0UpHyq9jhtyGRuN4exxef9IRBNkeEUJGy5R0JHyplqWpzXf96yQ8T9sk54/RsQfP4Ovj3bLzlWARpt3y51hSjjVpzhhlQGrCTLFmTUqAO/Nvzyb4p6TnOP1mOuiipMYiCShGkpXkH8Yu1G9JwH8DQMTxa6mRnmFMq7ypTMshhYMfV387IbeEfHv67y+Y+aW1Ji2XxV52vh7NkJauaCJMV9As7p8jso3MUWTwjr6TqHFqaOKTiQqP2dK1R7LDGgjzvOonMpuhevhf2dgyhRnEPVL9jKQ==',
  },
}
