// GENERATED by scripts/index-tiles.mjs. Do not edit.
export const TILE_META = {"source":"Urizen OneBit Tileset v2.0","src":"/tiles/urizen.png","tile":12,"pitch":13,"cols":206,"rows":50,"width":2679,"height":651} as const
